### ISSUE TITLE
[Bug] Sample code does not work when AzureAD is used as external login provider

### ISSUE THREAD

**Issue by ManuelHaas** [AzureAD/microsoft-identity-web#130]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.1-preview

**Where is the issue?**
Protected web APIs (Validating tokens)

Other? - please describe;
We already working with AzureAD as external login provider for SSO. We are working with .NET Core Identity Framework with a local user DB to manage roles and rights. Now we wanted to extend our App by requesting user data via MS Graph API. So I used the code of the samples in .NET Core docs to migrate our existing code. 

Correct me if I am wrong, but in this situation the call `services.AddSignIn(Configuration, "AzureAd");` is not suitable because then `signInManager.GetExternalAuthenticationSchemesAsync()` does not return the external AzureAd login provider that is used so far. So we used the already working `services.AddAuthentication` call:
```csharp
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                    .AddAzureAD(options => Configuration.Bind("AzureAd", options));
services.AddWebAppCallsProtectedWebApi(Configuration,
		initialScopes: new string[] { "user.read" })
	.AddInMemoryTokenCaches(); // Use a distributed token cache

// For instance, the distributed in-memory cache (not cleared when you stop the app):
services.AddDistributedMemoryCache();
```

Now when calling with a logged in user:
```csharp
var scopes = new[]{"user.read"};
string accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(scopes);
```
We get `Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.`

**Is this a new or existing app?**
 The app is in production, and I have upgraded to a new version of Microsoft Identity Web

**Expected behavior**
Working token cache when Azure Ad is external login provider.

**Actual behavior**
```
Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.
   at Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder.Validate()
   at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1.ValidateAndCalculateApiId()
   at Microsoft.Identity.Client.AbstractClientAppBaseAcquireTokenParameterBuilder`1.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1.ExecuteAsync()
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenOnBehalfOfUserFromCacheAsync(IConfidentialClientApplication application, IAccount account, IEnumerable`1 scopes, String tenant)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenOnBehalfOfUserFromCacheAsync(IConfidentialClientApplication application, ClaimsPrincipal claimsPrincipal, IEnumerable`1 scopes, String tenant)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String tenant)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String tenant)
   at Monitoring.Controllers.AccountController.ExternalLoginSignInAsync(ExternalLoginInfo info, Boolean isPersistent) in C:\XXX\AccountController.cs:line 463
   at Monitoring.Controllers.AccountController.ExternalLoginCallback(String returnUrl, String remoteError) in C:\XXX\AccountController.cs:line 372
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Possible Solution**
Support Azure AD as external login provider use case

**Comment by jmprieur** [comment]
@ManuelHaas : do I understand correctly that you are using Azure AD B2C?
In that's the case you probably want to have a look at this test: https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/B2CWebAppCallsWebApi

or these samples:

- https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/B2CWebAppCallsWebApi for signing-in users with B2C (and Azure AD being an external provider)
and  https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C for signing-in user with B2C and calling a Web API.

I don't think that B2C can call graph directly. @JasSuri can you please confirm?

**Comment by JasSuri** [comment]
This won’t work, you’re expecting that a user logged in through a B2C account can get a token to Graph API. That doesn’t work.

You need to treat this back end operation as if it was Azure AD and use client credentials with MSAL instead. Register an AAD App registration in your B2C directory and proceed as you would for an Azure AD client credentials call for a token to Graph API.

B2C users can’t get a token to Microsoft APIs, only your own APIs.
Rather than getting more info in the app via graph api, why aren’t you returning the required data in the B2C token in the first place? B2C tokens are fully customisable.

**Comment by ManuelHaas** [comment]
No, at least we do not use AAD B2C intentionally, but we may use its API.
We have taken this guide [(Quickstart: Add sign-in with Microsoft to an ASP.NET Core web app)](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp) as a basis for a single sign-in using Azure AD in conjunction with .NET Core Identity Framework. So we have multiple authentication provider and some users sign in directly (via .NET Core Identity Framework) and some via AAD.

Our application always connects to the customers own AAD - so no B2C.

But the failure was on my side. The call `services.AddAuthentication(AzureADDefaults.AuthenticationScheme).AddAzureAD(options => Configuration.Bind("AzureAd", options));` sets the scheme name to "AzureAD" but the new call `services.AddSignIn(Configuration, "AzureAd")` sets it to "OpenIdConnect".
So it was filtered by a subroutine in my code.

After I fixed the filter my App redirects to AAD and back. But for some reasons with the new provider the result of `await signInManager.GetExternalLoginInfoAsync()` is always null with the old provider it works. So I don't think its a problem with AzureAD settings. But this is  a different problem I have to investigate further.

Excuse the circumstances!

**Comment by jmprieur** [comment]
thanks for the update, @ManuelHaas
