### ISSUE TITLE
[Bug] AADB2C90088: error when using EditProfile 

### ISSUE THREAD

**Issue by avdv** [AzureAD/microsoft-identity-web#1307]
**Which version of Microsoft Identity Web are you using?**

Microsoft.Identity.Web 1.14.0

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

This is a new app.

**Repro**

I need to integrate with a third party provided AD B2C instance.

Implicit flow / hybrid flow is not permitted for my app and I cannot change this.

```csharp
builder
                .AddMicrosoftIdentityWebApp(
                    options =>
                    {
                        Configuration.Bind("AzureAd", options);

                        options.Events ??= new OpenIdConnectEvents();
                        var parentHandler = options.Events.OnRedirectToIdentityProvider;
                        options.Events.OnRedirectToIdentityProvider = async (context) =>
                        {
                            await parentHandler(context);

							// MS Identity Web insist on adding id_token for the EditProfile
                            // policy, although the options only have "code", which results in
                            // an error that the app is not allowed to use the implicit flow
                            context.ProtocolMessage.ResponseType = "code";
                        };
                    },
                    // see https://github.com/AzureAD/microsoft-identity-web/issues/133 on why cookieScheme is set to null
                    cookieScheme: null,
                    subscribeToOpenIdConnectMiddlewareDiagnosticsEvents: true
                )
                // according to https://github.com/AzureAD/microsoft-identity-web/wiki/Web-Apps#aadb2c90088-invalid_grant-error
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddInMemoryTokenCaches();
            ;
```

I have configured the `AzureAd` section in my appsettings.json:
```json
"AzureAd": {
    "Instance": "https://b2cxxxx.b2clogin.com",
    "ClientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "ClientSecret": "xxxxx",
    "Domain": "b2cxxxxx.onmicrosoft.com",
    "SignedOutCallbackPath": "/auth/signedout",
    "SignUpSignInPolicyId": "B2C_1A_signup_signin",
    "ResetPasswordPolicyId": "B2C_1A_PasswordReset",
    "EditProfilePolicyId": "B2C_1A_ProfileEdit",
    "ResponseType": "code",
    "Scope": [ "openid", "profile", "offline_access"],
    "CallbackPath": "/auth/callback"
  }
```

**Expected behavior**

I am trying to let the user edit her profile. After changing the data the user should return to the app. 

**Actual behavior**

The user is able to edit data, but after clicking "continue" an error is shown.

**Additional context / logs / screenshots**

```
warn: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.33.0.0 MSAL.NetCore Linux 5.12.9-zen1 #1-NixOS ZEN SMP Tue Jan 1 00:00:00 UTC 1980 [07/08 14:24:43.75 - a5db7876-15aa-4467-9b5d-9732988bc8b3] Request retry failed.
fail: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.33.0.0 MSAL.NetCore Linux 5.12.9-zen1 #1-NixOS ZEN SMP Tue Jan 1 00:00:00 UTC 1980 [07/08 14:24:43.78 - a5db7876-15aa-4467-9b5d-9732988bc8b3] Exception type: Microsoft.Identity.Client.MsalUiRequiredException
      , ErrorCode: invalid_grant
      HTTP StatusCode 400
      CorrelationId 
      
fail: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.33.0.0 MSAL.NetCore Linux 5.12.9-zen1 #1-NixOS ZEN SMP Tue Jan 1 00:00:00 UTC 1980 [07/08 14:24:43.78 - a5db7876-15aa-4467-9b5d-9732988bc8b3] Exception type: Microsoft.Identity.Client.MsalUiRequiredException
      , ErrorCode: invalid_grant
      HTTP StatusCode 400
      CorrelationId 
      
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.ConfidentialAuthCodeRequest.ExecuteAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[17]
      Exception occurred while processing message.
MSAL.NetCore.4.33.0.0.MsalUiRequiredException: 
        ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1A_signup_signin and Expected Value : B2C_1A_ProfileEdit
Correlation ID: 3c704cf4-1114-4793-a6b8-de74c8cc52b3
Timestamp: 2021-07-08 14:24:43Z

   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ConfidentialAuthCodeRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByAuthorizationCodeParameters authorizationCodeParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.TokenAcquisition.AddAccountToCacheFromAuthorizationCodeAsync(AuthorizationCodeReceivedContext context, IEnumerable`1 scopes, String authenticationScheme)
   at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder.<>c__DisplayClass11_1.<<WebAppCallsWebApiImplementation>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RunAuthorizationCodeReceivedEventAsync(OpenIdConnectMessage authorizationResponse, ClaimsPrincipal user, AuthenticationProperties properties, JwtSecurityToken jwt)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
        StatusCode: 400 
        ResponseBody: {"error":"invalid_grant","error_description":"AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1A_signup_signin and Expected Value : B2C_1A_ProfileEdit\r\nCorrelation ID: 3c704cf4-1114-4793-a6b8-de74c8cc52b3\r\nTimestamp: 2021-07-08 14:24:43Z\r\n"} 
        Headers: Cache-Control: private
```

**Comment by jmprieur** [comment]
@avdv Ms.Id.Web does specific things for the EditProfile case, and we believe that idtoken response type is required for this scenario?
@nickgmicrosoft is it still the case that B2C requires the idtoken response type?

**Comment by avdv** [comment]
> Ms.Id.Web does specific things for the EditProfile case, and we believe that idtoken response type is required for this scenario?

Thanks, @jmprieur. This would imply that one cannot use the EditProfile policy when the app is not permitted to use the hybrid flow?

**Comment by jmprieur** [comment]
Let's wait for @nickgmicrosoft 's reply, @avdv

**Comment by avdv** [comment]
I have updated to 1.14.1 in the meantime, but the problem persists.

Any updates on this?

**Comment by avdv** [comment]
Another update:

We have enabled the implicit grant flow for the App (both, Access Token and ID token are enabled) so I don't need to prevent the `id_token` anymore.

My code now looks like this:
```
// Configuration to sign-in users with Azure AD B2C
            builder
                // see https://github.com/AzureAD/microsoft-identity-web/issues/133 on why cookieScheme is set to null
                .AddMicrosoftIdentityWebApp(
                    options =>
                    {
                        Configuration.Bind("AzureAd", options);
                        options.Scope.Add(options.ClientId);
                    },
                    cookieScheme: null,
                    subscribeToOpenIdConnectMiddlewareDiagnosticsEvents: true
                );
            ;
        }
```
Here's the debug log output:
```
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      Begin OnRedirectToIdentityProviderAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         Sending OpenIdConnect message:
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ClientId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - EnableTelemetryParameters=True
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - EnableTelemetryParametersByDefault=True
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Nonce=637623682600139869.OTIwNGEwZDgtYjliMy00MjZlLTk4MDEtYzJlYzM3MTBjOTFiZTk3NjA4OTAtNTcyNy00OTUzLWJmZDYtNTg2YTg5YTZlNGQ5
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - RedirectUri=https://localhost:44316/protected/callback
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - RequestType=Authentication
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ResponseMode=form_post
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ResponseType=id_token
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Scope=openid profile offline_access xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - SkuTelemetryValue=ID_NETSTANDARD2_0
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - IssuerAddress=https://b2cxxxxxxx.b2clogin.com/b2cxxxxxxx.onmicrosoft.com/b2c_1a_signup_signin/oauth2/v2.0/authorize
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Parameters=System.Collections.Generic.Dictionary`2[System.String,System.String]
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - PostTitle=Working...
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Script=<script language="javascript">window.setTimeout('document.forms[0].submit()', 0);</script>
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ScriptButtonText=Submit
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ScriptDisabledText=Script is disabled. Click Submit to continue.
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      End OnRedirectToIdentityProviderAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      Begin OnMessageReceivedAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         Received from STS the OpenIdConnect message:
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - EnableTelemetryParameters=True
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - EnableTelemetryParametersByDefault=True
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - IdToken=...
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - RequestType=Authentication
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - SkuTelemetryValue=ID_NETSTANDARD2_0
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - IssuerAddress=
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Parameters=System.Collections.Generic.Dictionary`2[System.String,System.String]
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - PostTitle=Working...
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Script=<script language="javascript">window.setTimeout('document.forms[0].submit()', 0);</script>
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ScriptButtonText=Submit
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ScriptDisabledText=Script is disabled. Click Submit to continue.
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      End OnMessageReceivedAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      Begin OnTokenValidatedAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      End OnTokenValidatedAsync. 
info: RBS360.Areas.Identity.Controllers.AccountController[0]
      EditProfile OpenIdConnect - https://b2cxxxxxxx.b2clogin.com/
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      Begin OnRedirectToIdentityProviderAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         Sending OpenIdConnect message:
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ClientId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - EnableTelemetryParameters=True
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - EnableTelemetryParametersByDefault=True
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Nonce=637623682640715666.OGRkM2ExM2UtNTU0Yy00Zjk0LTk3YjAtZmRmM2VhMzBjYjM3NDEyNGQxM2EtYTM0Yi00ZWI5LWE5ZjMtODgyNTQwYmJhNjZm
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - RedirectUri=https://localhost:44316/protected/callback
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - RequestType=Authentication
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ResponseMode=form_post
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ResponseType=code id_token
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Scope=openid profile offline_access xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - SkuTelemetryValue=ID_NETSTANDARD2_0
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - IssuerAddress=https://b2cxxxxxxx.b2clogin.com/b2cxxxxxxx.onmicrosoft.com/b2c_1a_profileedit/oauth2/v2.0/authorize
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Parameters=System.Collections.Generic.Dictionary`2[System.String,System.String]
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - PostTitle=Working...
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Script=<script language="javascript">window.setTimeout('document.forms[0].submit()', 0);</script>
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ScriptButtonText=Submit
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ScriptDisabledText=Script is disabled. Click Submit to continue.
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      End OnRedirectToIdentityProviderAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      Begin OnMessageReceivedAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         Received from STS the OpenIdConnect message:
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Code=...
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - EnableTelemetryParameters=True
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - EnableTelemetryParametersByDefault=True
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - IdToken=...
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - RequestType=Authentication
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - SkuTelemetryValue=ID_NETSTANDARD2_0
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - IssuerAddress=
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Parameters=System.Collections.Generic.Dictionary`2[System.String,System.String]
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - PostTitle=Working...
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - Script=<script language="javascript">window.setTimeout('document.forms[0].submit()', 0);</script>
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ScriptButtonText=Submit
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
         - ScriptDisabledText=Script is disabled. Click Submit to continue.
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      End OnMessageReceivedAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      Begin OnTokenValidatedAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      End OnTokenValidatedAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      Begin OnAuthorizationCodeReceivedAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      End OnAuthorizationCodeReceivedAsync. 
fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[52]
      Message contains error: 'invalid_grant', error_description: 'AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1A_signup_signin and Expected Value : B2C_1A_ProfileEdit
      Correlation ID: 8be2cc5d-21bd-4dfe-b114-8ca98f4f8db9
      Timestamp: 2021-07-20 08:58:27Z
      ', error_uri: 'error_uri is null', status code '400'.
fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[17]
      Exception occurred while processing message.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_grant', error_description: 'AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1A_signup_signin and Expected Value : B2C_1A_ProfileEdit
Correlation ID: 8be2cc5d-21bd-4dfe-b114-8ca98f4f8db9
Timestamp: 2021-07-20 08:58:27Z
', error_uri: 'error_uri is null'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      Begin OnAuthenticationFailedAsync. 
dbug: Microsoft.Identity.Web.Resource.OpenIdConnectMiddlewareDiagnostics[0]
      End OnAuthenticationFailedAsync. 

```

**Comment by nickgmicrosoft** [comment]
@jmprieur , this doesn't seem to be an issue with the idtoken/implicit flow but rather something maybe about the known authority or the way the two different policy endpoints are being handled in the code?  If you think otherwise/it's an issue with the service let me know and I can ask an engineer on our side to help engagement.

**Comment by jennyf19** [comment]
@avdv Does this repro with the latest Id.Web? I believe this, or something similar, was fixed with the multiple authentication schemes work. Please re-open if the issue persists. Thanks.
