### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MikeBrownCygnia** [AzureAD/microsoft-identity-web#1361]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [X ] Sign-in users and call web APIs
* Web API
    * [X ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

**Repro**

I have used the example template code as provided by this repository. On my localhost, everything works as expected, my template app logs in via my Azure AD details and I can see my mail.read and user.read data on the /fetchdata page.

I publish the App to an Azure Web App service.

**Expected behavior**
I expect that when I publish the app, I will be able to login using my Azure AD details and access the app and expect this works exactly like localhost on the Azure Web App Service and also, works the same when accessing the /fetchdata page.

**Actual behavior**

I am able to log in as expected, however on /fetchdata page, the page flashes up the mail.read user.read data onto the page for a split second during prerender, and then the token is lost and the data is lost on final load. The token is blank and thus the call is authorized to graph.

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by MikeBrownCygnia** [comment]
Correction: The token is blank and thus the call is unauthorized to graph.

**Comment by MikeBrownCygnia** [comment]
Here is a video of the behaviour on the published Azure Web App

https://user-images.githubusercontent.com/88136063/127650114-01ea884f-8f69-44b2-8dbb-a7b82ec0286d.mp4

**Comment by MikeBrownCygnia** [comment]
Further to this, in that split second where I get the response, I can dump that value into a database, and then use that later in the lifecycle of the Blazor app. Very odd behaviour.

**Comment by jennyf19** [comment]
@MikeBrownCygnia Did you add the [redirect URI](https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-troubleshooting#if-your-app-works-locally-but-not-when-deployed)?

**Comment by MikeBrownCygnia** [comment]
> @MikeBrownCygnia Did you add the [redirect URI](https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-troubleshooting#if-your-app-works-locally-but-not-when-deployed)?

I have the redirect URI for the log in, do I need it elsewhere too? Thank you

**Comment by jennyf19** [comment]
@MikeBrownCygnia I see. The sample you are using is not correct, it needs to be updated. I would use one of our templates [here](https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template#use-the-web-app-blazor-server-template). Feel free to open an issue on the previous sample.

**Comment by MikeBrownCygnia** [comment]
> @MikeBrownCygnia I see. The sample you are using is not correct, it needs to be updated. I would use one of our templates [here](https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template#use-the-web-app-blazor-server-template). Feel free to open an issue on the previous sample.

Thank you once again Jenny.

This example uses a different method, and again, works perfectly in my local environment.

When I publish to Azure, it flashes quickly up on the screen with the result of the Graph Call, and then quickly refreshes itself and returns this error in the console. Seemingly, losing the token again after half a second. 

```
[2021-08-04T08:00:53.864Z] Error: Status Code: 0
Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.

 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'headers')
   at Microsoft.Identity.Web.AppServicesAuthenticationInformation.GetIdToken(IDictionary`2 headers)
   at Microsoft.Identity.Web.AppServicesAuthenticationTokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisitionAuthenticationProvider.AuthenticateRequestAsync(HttpRequestMessage request)
   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Identity.Web.MicrosoftIdentityConsentAndConditionalAccessHandler.HandleException(Exception exception)
   at blazorserver_graph.Pages.ShowProfile.OnInitializedAsync() in C:\blazorserver-graph\Pages\ShowProfile.razor:line 59
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

**Comment by jennyf19** [comment]
@MikeBrownCygnia can you provide a link to the code? might be easier. If private, please give permission to @jmprieur as well. thank you.
