### ISSUE TITLE
Set expire time on .AstNetCore.Cookies

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#1455]
My Web app uses Microsoft.Identity.Web and Microsoft.Identity.Web.UI to authentication the users. The response message for call to /signin-oidc sets cookie .AspNetCore.Cookies without specifying the expiration time:
```
	Set-Cookie: .AspNetCore.Cookies=CfDJ8EwQxa43GhNGjR6dPWgqRVSDDZkGxbjvsQxlXHLGxN6gWELPzTcoy9iO4y05fzUMIB7yKCClNbXouKUDPnAiMS4Lh5G2ci_RJGH1rXUCoihjNPJfHhYP2MkdeyuvXPICLart1CbQlriIqv4S6ofwcDAK7MQRSsVWBshHKiaWY37Y49pbNMPO99ArYCUfTwR5tmjEesMNO0oeX_IXpiVYRKf-eRnA4EFRnSTtLxiKDX0ozxqHQkwzdjGk0JVKO_RgZuWanQB1fFbsF8sv95ap_HdfQmMzFjyjofmzkO9-EUTBCfJ0PRdqtTWekjBHJIKiaIVEwRwaWZgRwlytwB2G4vjeGRVJiSDEbeGr1hHZuOgJsiItwdFPbGuJpTafqQkHnQmtAXVTN3B_bCWr6o1_mnneGIOz4_fj_Y9puhxvpWZent2mu16Gb9KfOnVOKkTAODkRsRtUE3owhAR_8T5erTTgpD8RQA92DunEJOALdFjrBxKp6MdLdImV5RlM6BIdW-ftUqe_ujleVQ67fgtVYaQnK-n_zHzszOelT7DhOBrnKnW0i4GloNlKjShYuAMTzN2uJJDMdJu19_iJcmvWWa7nDLowll8rluHFOM7LFh7Rzfh8DFZWKq5v6RpcP81cxJjmco64f4XeKXCulXUWxCXoUkaJkZ7rO1MpbwrfQeSzwFGNgTrs08KyjoHLKDgcxXWT12TDZA-gKdKkfsJjfATdcd0uHiCC2bOhioD4lLac_MdRM2ED_pCJHql9e9R_50epGuoSBGWniXvC4L9mXD1-2N0UrTsiMZ6o86nbXB0QAVNe22WQb2J_x-oKBWsmzqKTwrE_RAKs7-XHLL7HJQNDPdzxWePw9qRuUCTVGXRpAR482ht0Oy5zvrDgZ3tyICklLQ1EpznhUeSVNLFM6IYYxup_lWX5YKFwfUVGnY40qWKTyedbBeJkbO-PkxcIVH44BSQxqGnHFsQlNGPaUTPl11crQSIZqPssl-37P8xX0m33WPv-0zwN02vuSk__3iXXsWhHpZ-szNdUmb1HjTPLtj1BzK3jdtEdKDZ4ZPHTPDJV0kq3TTWdfnI1iznVYo0u6ZnzFklUIj-A4o8FrNB4MRqwbLo6spKUoMjQlVWUFWL3HnNPg6shSt9eNs4PokqdG7C8HHmvVOKaOf7PgMDncIGQIO31mVB4ykLn6tQxX4opJ0q3WlqpsSadXOD3x-odjtfaUTKQ8BdLK1TRDQhi3JcwY96mB5p4GsuTg5sScRCTOT9jHCrz0PK7TT320uyXbZKnj5r9NjFBL-95ZDzowBnMc3IEVIu_0Zs9ni1odiVa-WRjhfHrQPwMinLyhC6AN877Afuok6JZQ_11dfQEoqGU73CRMptFDbfKijwPs1RraYfalToTawkKWp2h4911n5Wlu_u8aTkE7-npndDYF4Svt5xla1qJsE6fVbgd1tcCQbwMYRBn1KIUBdVmasV5xYFlwOI7BAaMd-axXdTsbqYjtKCIY1jKS0UVGbIWEnzoyee89kzPZqaGkyNfeUZSeStQeGF3mbOSRR7OfCNtxuoTCjv_szOKe_Twcg0R-w-0blsUg9solj1Oz3xpt8-zkR324gb3GQ3Rcq6Nb67ytB5To8Z0riXBwmVQQYW7ymYiQD5EpWIFXz3MDwM-0sdl3I4SjuHWVygUpewRb1aDklrWGZ5YgkGmWMu2BoboJRBKHXWt5xY_e0nOfVoeUEJa1YVfd2n9_G_jAjxW95XnfDsR6CtzN21Gdwy594_eQq0VPi2npeW1tQVIkDF9KuEvXWe0gAQ3OpwIsPr7D6boch6R5DNA7YVbfNkiwO-0zU3Is57VCQeRM4qnIwhkPYiQ-ANgKF_93KrqKpgmka5hrs8aseBJZdSrdxQmjcQX8mZQdE4kBXNninKdlwCBIy1_BKGiQiMJryh4bkNYeeB-dVKeAjbxpmeaBQKQf7DGchyXEyCZy-SqOu1paCty2S66dh8A9iw4MEKFf8RrWfRQeovHKuKFUKmrRG3ASuACbA2hkOlf3b20-81m4x9tAZf6vVJHP1F6c0a6yjH_VQmi8tHaE3Fm-35V7bfsA5JtNKA3_AGjlcG88A_5yjBtbstTxlFFVkv_26qiI35XA0DaeoFfOTs3u6yG3B-uUsDk1sS8PW1qHBnRAwQIMIgSONblkAe2uNabCaoU4E0p4K7cDxD-YoQUIVV6DM5qtandwoOM5Z79mg-GNG7SpIn9kUjfI9rcpYW8ToZOzIjEKwTTxRIQ9xfA0Gyrjpu-cx0fvu0LehIT2nFHKkOZNYGgvVNFSjnqSjjhJIYGzO1QH9fchyUf4hxNQvrxyz4tFY-avwlUmnp82V2aAi6DjVzioGJpLEuPvvW71aa0ZLJCaN3gYeHAnUYvV7Z3tms1CAS7b0ISQgqxqk2a23Ibo9m90nW4PvDCqdOfWlzm5KQI1OSy-lzL4Q2c2Ur-QEjKsQbYY8fF3el8j0lCOJsm55PvJAyVZE3tcEyuI-7B_gAwhfretiYj-GOPCKL2_QWu9gQhzMvyZ5EcDHwbSqp6rgGJRX4ce5EJ5vtDFqeCS0Jv5ZR1OkTjKFotanNy3OVaiTy1; path=/AzureSsoService; secure; samesite=lax; httponly
```
The subsequently calls to my Web app includes the cookie in the request message and is automatically logged in without being asked about the Azure AD account and password.

I was trying to set expiration time on the cookie with `AddCookie` method below but the program throws an exception. My questions are:
1) Is there any reason not to set expiration time on cookie .AspNetCore.Cookies? 
2) What is the right way to get an expiration time on cookie .AspNetCore.Cookies?

```
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddCookie(options => options.Events.OnSignedIn = context =>
                {
                    context.Options.ExpireTimeSpan = TimeSpan.FromDays(1);
                    return Task.CompletedTask;
                })
                .AddMicrosoftIdentityWebApp(Configuration, "AzureAd")
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddInMemoryTokenCaches();
```

```
Unhandled exception. System.InvalidOperationException: Scheme already exists: Cookies
   at Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(String name, Action`1 configureBuilder)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__0(AuthenticationOptions o)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions`1 options, IDictionary`2 schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

**Comment by Ponant** [comment]
@WenningQiu use MaxAge and another extension in the lib

````csharp
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
 .AddMicrosoftIdentityWebApp(options =>
  {
      options.Instance = "https://xyz.com";
      //carry on
  }, c =>
  {
      c.AccessDeniedPath = "/denied";//Same as view
      c.Cookie.Name = "mycookie";
      c.Cookie.MaxAge = TimeSpan.FromDays(1);
      //carry on
  });
````

**Comment by WenningQiu** [comment]
@Ponant Thanks! That works.
