### ISSUE TITLE
[Bug] Reset Password and Edit Profile return with  'invalid_grant' only if GraphServiceClient is used

### ISSUE THREAD

**Issue by martinmeeser** [AzureAD/microsoft-identity-web#1508]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.19-preview

**Where is the issue?**
* Web app
    * [ x ] Sign-in users
    * [ x ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches

I am using Azure AD B2C with default b2c_susi and b2c_edit_profile.
I am also creating a GraphServiceClient like so:

        public static GraphServiceClient AddMicrosoftGraphClient(this IServiceCollection services, IConfigurationSection section)
        {
            string clientId = section.GetValue<string>("ClientId");
            string tenantId = section.GetValue<string>("TenantId");
            string clientSecret = section.GetValue<string>("ClientSecret");

            IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create(clientId)
                .WithTenantId(tenantId)
                .WithClientSecret(clientSecret)
                .Build();

            ClientCredentialProvider authProvider = new(confidentialClientApplication);
            GraphServiceClient graphServiceClient = new(authProvider);

            services.AddSingleton(graphServiceClient);
            return graphServiceClient;
        }

If I comment out the whole function body and just return null, then the problem disappears. This is 100% reproducible.

**Is this a new or an existing app?**
This is a new web app in beta testing for around 3 month. Not clear if the problem came through an update.

**Expected behavior**
Reset password and edit profile user flows work without issues, with or without a GraphServiceClient instance around.

**Actual behavior**
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Error: Exception occurred while processing message.

Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_grant', error_description: 'AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1_susi and Expected Value : B2C_1_edit
Correlation ID: 72149a23-5e4c-4acf-a473-84aafb585efa
Timestamp: 2021-11-01 11:48:15Z
', error_uri: 'error_uri is null'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by martinmeeser** [comment]
Update: The issue appears as soon as I add 
"ClientSecret": "jjj", 
    "TenantId": "jkjkl", 

to application.json.

Will try to instanciate graphclient from different config section.

so how to reproduce is: 
add valid client secret and tenantid to appsettings "AzureAdB2C"

**Comment by martinmeeser** [comment]
Using two different sections in app-settings solved the issue. Not sure if I would still call it a bug.
It DID cost me a lot of time two get to the bottom of that. I must be made clearer in documentation IMHO.

Also I think the error message is not helping.

**Comment by jmprieur** [comment]
@martinmeeser what does your other section do? is it an AAD app? or a B2C app?
