### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wwy12321** [AzureAD/microsoft-identity-web#1765]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

1.25.0

**Where is the issue?**
* Web app
If locally run dotnet app.dll everything is ok, but if package into an image and run in docker or kubernetes, each request will occur error:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentNullException: IDW10106: The 'ClientId' option must be provided.
         at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options)
         at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__3(OpenIdConnectOptions options, IServiceProvider serviceProvider, IOptionsMonitor'1 mergedOptionsMonitor, IOptionsMonitor'1 msIdOptionsMonitor, IOptions'1 msIdOptions)
         at Microsoft.Extensions.Options.ConfigureNamedOptions'5.Configure(String name, TOptions options)
         at Microsoft.Extensions.Options.OptionsFactory'1.Create(String name)
         at Microsoft.Extensions.Options.OptionsMonitor'1.<>c__DisplayClass10_0.<Get>b__0()
         at System.Lazy'1.ViaFactory(LazyThreadSafetyMode mode)
      --- End of stack trace from previous location ---
         at System.Lazy'1.CreateValue()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler'1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Repro**
appsettings.json
```json
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "xxx",
    "TenantId": "xxx",
    "ClientId": "xxx",
    "CallbackPath": "/signin-oidc",
    "ClientSecret": "xxx",
    "ClientCertificates": []
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "MicrosoftGraph": {
    "BaseUrl": "https://graph.microsoft.com/v1.0",
    "Scopes": "user.read"
  }
}
```
appsettings.Production.json (set in configmap)
```json
{
  "ConnectionString": "AccountEndpoint=https://xxx.documents.azure.com:443/;AccountKey=xxx;"
}
```

Dockerfile
```Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY ./apprelease /home/app
```

**Comment by wwy12321** [comment]
I created  other 2 apps in Visual Studio, both app are Blazor server and ASP.NET core app, and enabled the "Microsoft Identity Platform" as Authentication type, and Enabled "Microsoft Graph" in guard. And didn't modify any codes.
Copy the published files into container will get same result as above. And running locally is OK.

**Comment by svrooij** [comment]
Are you sure the `appsettings*.json` files are copied to the container? Just a quick check. Had some issues with that in the past. Just start the container interactive with a terminal and check the folder contents, or add `ls -la /app` to your dockerfile and do a build.

And apart from that what happens if you set the environment variables in the container. I'm curious to whether or not this is an issue with this library or a configuration error. Like:

- `AZUREAD__INSTANCE` = `https://login.microsoftonline.com/`
- `AZUREAD__TENANTID` = `xxx`
- ...

(mind the double underscore `__` as a section seperator.)

**Comment by wwy12321** [comment]
Hi @svrooij ,
Thanks for reply, I have pulled the container image and checked the file is exists in there. And I have created a new project to make sure the issue is there, here are the steps:

1. In visual studio right click the solution and choose Add - New project. Then select Blazor server (ASP.NET core web app got same result), and in wizard choose Microsoft identity platform for Authentication type. Then create the project, after install some required component, follow the steps to connect this project to AAD app. Finally open the appsettings.json to make sure the 2 ids and domain are fetched and saved in that file.
2. Open terminal and locate to root path of project, and start to build, `dotnet restore`, `dotnet publish -o ./apprelease -c release`, then start the app `dotnet /apprelease/BlazorApp2.dll`, and open the webpage to make sure the web app is OK.
3. Start the docker and enter `docker pull mcr.microsoft.com/dotnet/aspnet:6.0`, `docker run --name temp -itd -p 5001:80 mcr.microsoft.com/dotnet/aspnet:6.0`, `docker cp ./apprelease/. temp:/home/app`, then in the container terminal `ls /home/app` to check the files are there, then `dotnet /home/app/BlazorApp2.dll` to start app in container.
4. Open that page in browser will see 500 result, and in container terminal will see the error:

**Comment by wwy12321** [comment]
Hi @svrooij , I'm checking is there anything update about this issue, because this issue has blocked our delivery progress for few days, so I was hoping you can give me a solution or fix this issue ASAP, thanks.

**Comment by svrooij** [comment]
@wwy12321 I'm not in the MSAL team. I just noticed an issue that looked similar to mine few months ago (settings not loaded docker). I hope someone else can help you out.

**Comment by wwy12321** [comment]
@svrooij  nvm, no one following my issue except you, and it seems our project gonna blocked at least for another few month =D, anyway, thanks for help.

**Comment by jmprieur** [comment]
@tratcher who could help with this?  (deploying in a container does not find the Appsettings.json)

**Comment by wwy12321** [comment]
> @Tratcher who could help with this? (deploying in a container does not find the Appsettings.json)

So, @Tratcher is responsible for MIW?

**Comment by jmprieur** [comment]
No, @wwy12321. But ASP.NET Core running in containers is not MIW.

**Comment by wwy12321** [comment]
@jmprieur I think it's all about MIW's issue, ASP.NET core is good, MIW has something wrong with it.

**Comment by jmprieur** [comment]
> I created other 2 apps in Visual Studio, both app are Blazor server and ASP.NET core app, and enabled the "Microsoft Identity Platform" as Authentication type, and Enabled "Microsoft Graph" in guard. And didn't modify any codes. Copy the published files into container will get same result as above. And running locally is OK.

@wwy12321 
Visual Studio creates a client secret to call Microsoft Graph. Did you add it to your appsettings.json or to some secret store on the container? (it's visible from the "Manage User Secrets" contextual command on the project.

**Comment by wwy12321** [comment]
@jmprieur , the following comments I didn't enable the "Microsoft Graph" but still get the error:
`1. In visual studio right click the solution and choose Add - New project. Then select Blazor server (ASP.NET core web app got same result), and in wizard choose Microsoft identity platform for Authentication type. Then create the project, after install some required component, follow the steps to connect this project to AAD app. Finally open the appsettings.json to make sure the 2 ids and domain are fetched and saved in that file.`
The client secret is about getting user profile by MG, but now the errors I got is about authentication, i.e. no page can open successfully not only the user profile page, even if I didn't enable the "Microsoft Graph" the app still can't run in container. 
I beg you try my steps that mentioned and check is the bug there or not.

**Comment by jmprieur** [comment]
@svrooij [wwy12321](https://github.com/wwy12321) Can you please try without the Domain in your appsettings.json ? (only the TenantId) ?

**Comment by svrooij** [comment]
@jmprieur I was only trying to help. We are not having this issue.

@wwy12321 they might have found a solution for you.

**Comment by wwy12321** [comment]
@jmprieur  good news, remove the domain still got the error, ha.
<img width="867" alt="1" src="https://user-images.githubusercontent.com/33349734/179210353-22b82709-10f0-4c61-aef0-4238cf538aaf.png">

**Comment by ibnuda** [comment]
I am reporting the same issue. though my app doesn't even run as dll. Tried to debug the library itself. it seems `mergedOptions` [1] is an empty dict.

version used: 2.7.0 and master (for debugging).

error:
```
System.ArgumentNullException: IDW10106: The 'ClientId' option must be provided. 
   at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options) in C:\Users\YoMommaIsSoFat\source\repos\microsoft-identity-web\src\Microsoft.Identity.Web\MergedOptionsValidation.cs:line 15

   at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__3(OpenIdConnectOptions options, IServiceProvider serviceProvider, IMergedOptionsStore mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions) in C:\Users\IbnuAJI\source\repos\microsoft-identity-web\src\Microsoft.Identity.Web\WebAppExtensions\MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs:line 291
   at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

[1] https://github.com/AzureAD/microsoft-identity-web/blob/b03882c59c100fe9bb50a6e626aeda49e7a217ca/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L289

**Comment by ibnuda** [comment]
I am reporting the same issue. though my app doesn't even run as dll. Tried to debug the library itself. it seems `mergedOptions` [1] is an empty dict.

version used: 2.7.0 and master (for debugging).

error:
```
System.ArgumentNullException: IDW10106: The 'ClientId' option must be provided. 
   at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options) in C:\Users\YoMommaIsSoFat\source\repos\microsoft-identity-web\src\Microsoft.Identity.Web\MergedOptionsValidation.cs:line 15

   at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__3(OpenIdConnectOptions options, IServiceProvider serviceProvider, IMergedOptionsStore mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions) in C:\Users\YoMommaIsSoFat\source\repos\microsoft-identity-web\src\Microsoft.Identity.Web\WebAppExtensions\MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs:line 291
   at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

[1] https://github.com/AzureAD/microsoft-identity-web/blob/b03882c59c100fe9bb50a6e626aeda49e7a217ca/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L289

**Comment by wwy12321** [comment]
> Is this repro'ing on 3.0.x?

Still the same..
![screen](https://github.com/user-attachments/assets/54951b47-7b4b-402c-846f-e8854782894e)

**Comment by ibruynin** [comment]
Hi all

we see this error IDW10106: “The ClientId option must be provided as well.
The circumstances are maybe a bit more specific, bear with me:

- Running MIW on latest version 3.6.2
- dotnet 9.0 native AOT compilation enabled
    - PublishAot: true
    - staticwebassetsenabled: false
    - runtimeIdentifiers: linux-x64;win-x64
- app is running in docker compose, with AzureAd_* parameters defined as environment variables
- entrypoint is defined as: “/<aot.compiled.app.name>” and not “dotnet”, “nonaot.compiled.app.name.dll”

Now, the interesting part…
If we 
- disable the PublishAot from true to false
- change the docker entrypoint back to “dotnet”, “nonaot.compiled.app.name.dll”
… it DOES work in docker.

In both cases, console.writeline(builder.Configuration.GetSection(“AzureAd”).GetValue<string>(“ClientId”) does print the ClientId to the console. So the binding is ok, in both cases.

Our stacktrace also mentions the `MicrosoftIdentityWebApiAuthentationBuilderExtensions` and the `MergedOptionsValidation.Validation`

Does this help troubleshooting? Any bells that ring?

**Comment by ibruynin** [comment]
The plot thickens….

when combining the AddMicrosoftIdentityWebApi(configureJwtBearerOptions, configureMicrosoftIdentityOptions) with a class that does postconfiguration with DI to use the IOptions pattern, it fails again with the same error as before.

```
services.AddSingleton<IPostConfigureOptions<JwtBearerOptions>, classthatdoesconfigurejwtbeareroptions>();
services.AddSingleton<IPostConfigureOptions<MicrosoftIdentityOptions>, classthatdoesconfiguremicrosoftidentityoptions>();
services…AddMicrosoftIdentityWebApi(configureJwtBearerOptions: t1 => {}, configureMicrosoftIdentityOptions: t2 => {});
```

Doing this seems to call the method using the (JwtBearerOptions, IServiceProvider, IMergedOptionsStore, IOptionsMonitor) overload again, resulting in failure as before.

Only using the postconfigure mechanism for JwtBearerOptions and explicitly configuring the t2 lambda, does work.
So we’ll do that for now - but this needs further investigation because something’s off (@jennyf19 are you following this?)

**Comment by ibnuda** [comment]
ay mate, it's been more than a year, yea? i think i side-stepped my problem back then by adding a dummy config like this:

```
services.AddAuthentication(options => {
    // do the needful
})
    .AddOpenIdConnect(options => {
        // it's a dummy config
        options.AccessDeniedPath = "/access-denied-from-remote";
        options.Authority = "https://example.com";
        options.CallbackPath = "/signin-oidc";
        options.ClaimsIssuer = "it was i, dio!";
        options.ClientId = "empty";
        options.ClientSecret = "secret";
        options.ConfigurationManager = new ConfigurationManager < OpenIdConnectConfiguration > (
            "https://example.com/.well-known/openid-configuration",
            new OpenIdConnectConfigurationRetriever()
        );
    })
```

but again, i'm not entirely sure if it was the workaround for the situation or not.
