### ISSUE TITLE
Using Microsoft.Identity.Web and Microsoft.Identity.Web.UI on non-Microsoft IDPs

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#1789]
Microsoft.Identity.Web is a library for integrating with the [Microsoft identity platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/) (formerly Azure AD v2.0 endpoint) and [AAD B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/). How does it work with other non-Microsoft identity platforms that support OAuth and OpenID Connect protocols? The reason I am asking is we already have a working solution based on  Microsoft.Identity.Web and Microsoft.Identiry.Web.UI for AzureAD, I am interested in finding out if it works with other identity platforms such as NetIQ.

**Comment by jmprieur** [comment]
@WenningQiu : are you building a web app? or web API?
Did you try to use Microsoft.identity.web with NetIQ? This might work if you provide the authority (instead of instance and tenant).

**Comment by WenningQiu** [comment]
@jmprieur Yes I am trying to use Microsoft.Identiry.Web with NetIQ to secure access to a Web application. Will you be able to provide links to authority samples and/or documentation?

**Comment by WenningQiu** [comment]
I tried setting Authority to NetIQ auth endpoint and not using TenantId and Instance, but got an exception about missing "Instance" option. I am using version 1.24.1.

```
   "Test": {
    "Authority": "https://<hostname>/nidp/oauth/nam/authz",
    "ClientId": "********-****-****-****-************",
    "ClientSecret": "**********************",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc"
  },
 ```

```
 
 
 
      An unhandled exception has occurred while executing the request.
      System.ArgumentNullException: IDW10106: The 'Instance' option must be provided.
         at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options)
         at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__3(OpenIdConnectOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions)
         at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.get_Value()
         at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
         at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by WenningQiu** [comment]
Got a different exception with the following configuration:

```
  "Test": {
    "Instance": "https://<hostname>/",
    "TenantId": "nidp/oauth/nam/authz",
    "ClientId": "********-****-****-****-************",
    "ClientSecret": "**********************",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc"
  }
```

```
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
       ---> System.IO.IOException: IDX20807: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. HttpResponseMessage: '[PII of type 'System.Net.Http.HttpResponseMessage' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', HttpResponseMessage.Content: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
         at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAlwaysRunResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by WenningQiu** [comment]
A working NetIQ URL to request Authorization Code looks like "https://<hostname>/nidp/oauth/nam/authz?response_type=code&client_id=********-****-4e43-b72a-111d7f04ad38&redirect_uri=https://<app_hostname>/signin-oidc&scope=profile+email&nonce=ab8932b6&state=AB32623HS".

Below is a similar URL generated by Microsoft.Identity.Web for AzureAD. Perhaps we can get the exact URL path generated with Authority if we can get around Microsoft.Identity.Web validation logic. However I am not sure if there is a way to not generate those query parameters that perhaps are required by AzureAD but not NetIQ. The best hope is for NetIQ to ignore those extra query parameters.

https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize?client_id=********-****-408d-ad86-14602788f346&redirect_uri=https%3A%2F%2F<app_hostname>%2FAzureSsoService%2Fsignin-oidc&response_type=code&scope=openid%20profile%20offline_access&code_challenge=6QrqAgYdmQuM5WXN_dFk3JfhnjRlGeLqyWfblmKCO8g&code_challenge_method=S256&response_mode=form_post&nonce=637920633821060026.N2E2YzE2NWItYzc0Ny00MjMwLTk2ODItZjUwN2EzMzRmMDZlNThjODkzNjctODkyNS00YzMyLTk5ZTAtZGIyZjA3NDU3OGY4&client_info=1&x-client-brkrver=IDWeb.1.24.1.0&state=CfDJ8BCvefs1RH5Gg0jc5u3CXEqpuWre9pqpUvlgt2zf5lTD6J02eKVwPukkK88Xcp8QZcaD3PkLHRnJUeka8pCSxXwQHbcEJfbmfv4jqa7cs0jjku3Rj_xqhNmbs0TATsGnPSTXhA-lYyW7AwyFqGoBiUG5tFgFLEw1C6U6EY4jiA5Hb17n-0R4NqlTbDnSMzyCtMkFrcBUt-jGLJN4U6Dti9TtrZzNo4NqwQag7Ua8H5znEd4Yqsh8KYxjPNenFeAV0gkaS3DxFQPyvMNwdtjvMb-X-I5Ux-FXQb75l4wH-PYncFZOF8s_9R8ie-SN7zRIpEaXfCcTPEsTiAfT_5j4aYNyCnRU-sGqtXmPS6NQNlAqCalfkZWbdHqtTkcKaztgfG2o2nTLYFFUAVp851jOY1rq3ZNxSS_kUnOy54WYkJUKW6ZFvutwYkH8NcZdlkR8gQQR8BsVHv0pisvbZjjZJ6c&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.17.0.0

**Comment by WenningQiu** [comment]
I bypassed the validation logic in MergedOptionsValidation class but still got exception with the configuration below. It appears that Microsoft.Identity.Web, like the name and its documentation suggests, is tightly coupled with Microsoft Identity Platform and is not ready to support other IDPs.

```
  "Test": {
    "Authority": "https://<hostname>/nidp/oauth/nam/authz",
    "ClientId": "********-****-****-****-************",
    "ClientSecret": "**********************",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc"
  }
```
```
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
       ---> System.IO.IOException: IDX20807: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. HttpResponseMessage: '[PII of type 'System.Net.Http.HttpResponseMessage' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', HttpResponseMessage.Content: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
         at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAlwaysRunResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by jmprieur** [comment]
@WenningQiu : Is NetIQ OIDC compliant? 
Would you mind enabling PII to see the endpoint that Identity.Model tried to reach?

**Comment by WenningQiu** [comment]
NetIQ should be OIDC compliant: https://www.netiq.com/documentation/access-manager-45-developer-documentation/administration-rest-api-guide/data/oauth-openid-connect-api.html

After enabling PII in logs (IdentityModelEventSource.ShowPII = true), the exception show the endpoint it tries to reach:
```
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.esso-uat.charter.com:8443/nidp/oauth/nam/authz/v2.0/.well-known/openid-configuration'.
       ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'https://login.esso-uat.charter.com:8443/nidp/oauth/nam/authz/v2.0/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 404, ReasonPhrase: '', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        X-Frame-Options: SAMEORIGIN
        Strict-Transport-Security: max-age=31536000
        X-Content-Type-Options: nosniff
        X-XSS-Protection: 1; mode=block
        Date: Thu, 30 Jun 2022 13:33:42 GMT
        Set-Cookie: BIGipServernetiq_idp_8443_pool=1420069006.64288.0000; path=/; Httponly; Secure
        Content-Type: text/html
        Content-Length: 120
      }', HttpResponseMessage.Content: '<!DOCTYPE html>
<html>
<head>
<title>Response</title>
</head>
<body>
<h2>Error: HTTP 404 Not Found</h2>
</body>
</html>
'.
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
         at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAlwaysRunResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by jmprieur** [comment]
@WenningQiu : you need to understand what's the URL of the open id connect metadata document in NetIQ. It's not the one that is computed from the authority.

**Comment by WenningQiu** [comment]
I was able to get further with MetadataAddress set to the metadata endpoint URL and 

1. Bypass checking of Instance in TokenAcquisition.GetOptions()
2. Prevent NullReferenceException from being thrown in MergedOptions.PrepareAuthorityInstanceForMsal()

I was able to get past the authentication dialog (user name, password and MFA), but got the following error when the call was redirected to the callback URL which I believe is the last step. It is really close.

```
  "Test": {
    "Authority": "https://<hostname>:8443/nidp/oauth/nam/authz",
    "MetadataAddress": "https://<hostname>:8443/nidp/oauth/nam/.well-known/openid-configuration",
    "ClientId": "********-****-****-****-************",
    "ClientSecret": "**********************",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc"
  }
```

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost/AzureSsoService/signin-oidc application/x-www-form-urlencoded 1388
info: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.42.0.0 MSAL.NetCore .NET 6.0.4 Microsoft Windows 10.0.19044 [2022-07-05 19:42:49Z - 51354697-187e-4e33-9052-3cabcd087ac7] MSAL MSAL.NetCore with assembly version '4.42.0.0'. CorrelationId(51354697-187e-4e33-9052-3cabcd087ac7)
info: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.42.0.0 MSAL.NetCore .NET 6.0.4 Microsoft Windows 10.0.19044 [2022-07-05 19:42:49Z - 51354697-187e-4e33-9052-3cabcd087ac7]
      === Request Data ===
      Authority Provided? - True
      Scopes -
      Extra Query Params Keys (space separated) -
      ApiId - AcquireTokenByAuthorizationCode
      IsConfidentialClient - True
      SendX5C - False
      LoginHint ? False
      IsBrokerConfigured - False
      HomeAccountId - False
      CorrelationId - 51354697-187e-4e33-9052-3cabcd087ac7
      UserAssertion set: False
      LongRunningOboCacheKey set: False

info: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.42.0.0 MSAL.NetCore .NET 6.0.4 Microsoft Windows 10.0.19044 [2022-07-05 19:42:49Z - 51354697-187e-4e33-9052-3cabcd087ac7] === Token Acquisition (ConfidentialAuthCodeRequest) started:
         Scopes:
warn: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.42.0.0 MSAL.NetCore .NET 6.0.4 Microsoft Windows 10.0.19044 [2022-07-05 19:42:49Z - 51354697-187e-4e33-9052-3cabcd087ac7] Only in-memory caching is used. The cache is not persisted and will be lost if the machine is restarted. It also does not scale for a web app or web API, where the number of users can grow large. In production, web apps and web APIs should use distributed caching like Redis. See https://aka.ms/msal-net-cca-token-cache-serialization
   => SpanId:9801e1f9cd2c8edd, TraceId:13905b616b0b438667c40c75a36df270, ParentId:0000000000000000 => RequestPath:/AzureSsoService/signin-oidc RequestId:8000005c-0004-fb00-b63f-84710c7967bb
False MSAL 4.42.0.0 MSAL.NetCore .NET 6.0.4 Microsoft Windows 10.0.19044 [2022-07-05 19:42:49Z - 51354697-187e-4e33-9052-3cabcd087ac7] Only in-memory caching is used. The cache is not persisted and will be lost if the machine is restarted. It also does not scale for a web app or web API, where the number of users can grow large. In production, web apps and web APIs should use distributed caching like Redis. See https://aka.ms/msal-net-cca-token-cache-serialization

info: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.42.0.0 MSAL.NetCore .NET 6.0.4 Microsoft Windows 10.0.19044 [2022-07-05 19:42:49Z - 51354697-187e-4e33-9052-3cabcd087ac7] [Region discovery] Not using a regional authority.
info: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.42.0.0 MSAL.NetCore .NET 6.0.4 Microsoft Windows 10.0.19044 [2022-07-05 19:42:49Z - 51354697-187e-4e33-9052-3cabcd087ac7] Fetching instance discovery from the network from host login.microsoftonline.com.
info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET https://login.microsoftonline.com:8443/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.esso-uat.charter.com%3A8443%2Fnidp%2Foauth2%2Fv2.0%2Fauthorize
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET https://login.microsoftonline.com:8443/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.esso-uat.charter.com%3A8443%2Fnidp%2Foauth2%2Fv2.0%2Fauthorize
fail: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.42.0.0 MSAL.NetCore .NET 6.0.4 Microsoft Windows 10.0.19044 [2022-07-05 19:44:29Z - 51354697-187e-4e33-9052-3cabcd087ac7] The HTTP request failed or it was canceled. The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
   => SpanId:9801e1f9cd2c8edd, TraceId:13905b616b0b438667c40c75a36df270, ParentId:0000000000000000 => RequestPath:/AzureSsoService/signin-oidc RequestId:8000005c-0004-fb00-b63f-84710c7967bb
False MSAL 4.42.0.0 MSAL.NetCore .NET 6.0.4 Microsoft Windows 10.0.19044 [2022-07-05 19:44:29Z - 51354697-187e-4e33-9052-3cabcd087ac7] The HTTP request failed or it was canceled. The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

**Comment by WenningQiu** [comment]
I am convinced that Microsoft.Identity.Web is tightly coupled with Microsoft Identity Platform and is not intended to support other IDPs in its current state. There are two ways to integrate an application with other IDPs:

1. Use Microsoft.AspNetCore.Authentication.OpenIdConnect and other related packages directly.
2. Use Azure AD B2C service which is supported by Microsoft.Identity.Web. Since my application already uses Microsoft.Identity.Web package, this seems to be the most reasonable (simplest) approach for me.

**Comment by jmprieur** [comment]
Thanks @WenningQiu.
Shall we close this question?
