### ISSUE TITLE
Unable to read Certificate from KeyVault when running in MacOS (M2 chip)

### ISSUE THREAD

**Issue by luismanez** [AzureAD/microsoft-identity-web#1976]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.25.1

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Distributed caches

### Description

I have a web api secured by AAD that calls Microsoft Graph API (downstream API).

```sharp
services.AddMicrosoftIdentityWebApiAuthentication(configuration)
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddMicrosoftGraph()
                .AddDistributedTokenCaches();
```

To call Graph, I'm using a Certificate in Azure KeyVault. The certificate is configured in settings.json:

```xml
    "ClientCertificates": [
      {
        "SourceType": "KeyVault",
        "KeyVaultUrl": "https://my-kv.vault.azure.net/",
        "KeyVaultCertificateName": "MyCertificate"
      }
    ]
```

Everything is working perfectly fine when running in Windows, and actually, the API is already in production, deployed to Azure. However, I'm trying to run it locally in a new __MacBook Air M2__ (Ventura 13.0.1) and I get the following error when _Microsoft.Identity.Web_ is trying to read the certificate from Azure KeyVault:

> System.PlatformNotSupportedException: This platform does not support loading with EphemeralKeySet. Remove the flag to allow keys to be temporarily created on disk.
         at Internal.Cryptography.Pal.AppleCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
         at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
         at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
         at Microsoft.Identity.Web.DefaultCertificateLoader.LoadFromBase64Encoded(String certificateBase64, X509KeyStorageFlags x509KeyStorageFlags)
         at Microsoft.Identity.Web.DefaultCertificateLoader.LoadFromKeyVault(String keyVaultUrl, String certificateName, X509KeyStorageFlags x509KeyStorageFlags)
         at Microsoft.Identity.Web.DefaultCertificateLoader.LoadIfNeeded(CertificateDescription certificateDescription)
         at Microsoft.Identity.Web.DefaultCertificateLoader.<>c__DisplayClass5_0.<LoadFirstCertificate>b__0(CertificateDescription c)
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
         at Microsoft.Identity.Web.DefaultCertificateLoader.LoadFirstCertificate(IEnumerable`1 certificateDescriptions)
         at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
         at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
         at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
         at Microsoft.Identity.Web.TokenAcquisitionAuthenticationProvider.AuthenticateRequestAsync(HttpRequestMessage request)
         at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
         at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
         at Microsoft.Graph.UserTransitiveMemberOfCollectionWithReferencesRequest.GetAsync(CancellationToken cancellationToken)
         at Atlas.Connex.Infrastructure.Repositories.GraphUserRepository.IsCurrentUserTemplatesAdmin() in /Users/luisman/dev/atlas/src/Infrastructure/Connex.Infrastructure/Repositories/GraphUserRepository.cs:line 82
         at Atlas.Connex.Application.Templates.Queries.GetAllTemplates.GetAllTemplatesQueryHandler.Handle(GetAllTemplatesQuery request, CancellationToken cancellationToken) in /Users/luisman/dev/atlas/src/Core/Connex.Application/Templates/Queries/GetAllTemplates/GetAllTemplatesQuery.cs:line 47
         at Atlas.Connex.Application.Common.Behaviour.LoggingBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /Users/luisman/dev/atlas/src/Core/Connex.Application/Common/Behaviour/LoggingBehaviour.cs:line 43
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at Atlas.Connex.Api.Controllers.TemplatesController.GetAllTemplates(AllTemplateRequest body) in /Users/luisman/dev/atlas/src/Api/Connex.Api/Controllers/TemplatesController.cs:line 316
         at lambda_method81(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

### Reproduction steps

1. Secure a WebAPI
2. Configure to call MS Graph API as downstream API
3. Configure an Azure KeyVault with certificate
4. Setup API to read the certificate from Az KeyVault

### Error message

System.PlatformNotSupportedException: This platform does not support loading with EphemeralKeySet. Remove the flag to allow keys to be temporarily created on disk.
         at Internal.Cryptography.Pal.AppleCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
         at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
         at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
         at Microsoft.Identity.Web.DefaultCertificateLoader.LoadFromBase64Encoded(String certificateBase64, X509KeyStorageFlags x509KeyStorageFlags)
         at Microsoft.Identity.Web.DefaultCertificateLoader.LoadFromKeyVault(String keyVaultUrl, String certificateName, X509KeyStorageFlags x509KeyStorageFlags)
         at Microsoft.Identity.Web.DefaultCertificateLoader.LoadIfNeeded(CertificateDescription certificateDescription)
         at Microsoft.Identity.Web.DefaultCertificateLoader.<>c__DisplayClass5_0.<LoadFirstCertificate>b__0(CertificateDescription c)
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
         at Microsoft.Identity.Web.DefaultCertificateLoader.LoadFirstCertificate(IEnumerable`1 certificateDescriptions)
         at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
         at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
         at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
         at Microsoft.Identity.Web.TokenAcquisitionAuthenticationProvider.AuthenticateRequestAsync(HttpRequestMessage request)
         at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
         at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
         at Microsoft.Graph.UserTransitiveMemberOfCollectionWithReferencesRequest.GetAsync(CancellationToken cancellationToken)
         at Atlas.Connex.Infrastructure.Repositories.GraphUserRepository.IsCurrentUserTemplatesAdmin() in /Users/luisman/dev/atlas/src/Infrastructure/Connex.Infrastructure/Repositories/GraphUserRepository.cs:line 82
         at Atlas.Connex.Application.Templates.Queries.GetAllTemplates.GetAllTemplatesQueryHandler.Handle(GetAllTemplatesQuery request, CancellationToken cancellationToken) in /Users/luisman/dev/atlas/src/Core/Connex.Application/Templates/Queries/GetAllTemplates/GetAllTemplatesQuery.cs:line 47
         at Atlas.Connex.Application.Common.Behaviour.LoggingBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /Users/luisman/dev/atlas/src/Core/Connex.Application/Common/Behaviour/LoggingBehaviour.cs:line 43
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at Atlas.Connex.Api.Controllers.TemplatesController.GetAllTemplates(AllTemplateRequest body) in /Users/luisman/dev/atlas/src/Api/Connex.Api/Controllers/TemplatesController.cs:line 316
         at lambda_method81(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

### Relevant code snippets

```csharp
Already included in Bug description
```

### Expected behavior

Certificate is loaded from KeyVault

**Comment by luismanez** [comment]
Any thoughts here please @jennyf19 @jmprieur ?? as a workaround, it works installing the certificate in my Mac, and configuring MS Identity web using Thumbprint:

```json
{
  "SourceType": "StoreWithThumbprint",
  "CertificateStorePath": "CurrentUser/My",
  "CertificateThumbprint": "AAAAAA......."
}
```

**Comment by jmprieur** [comment]
@luismanez : which target framework do you use to build your app for Mac?

**Comment by luismanez** [comment]
Target framework: .net 6.0
dotnet --version => 6.0.403

Thanks.

**Comment by jennyf19** [comment]
@luismanez did you try lowercasing this `MyCertificate` and does the problem still exist on the latest Id Web 2.13.3?

**Comment by luismanez** [comment]
@jennyf19 I can confirm lowercasing the name does not solve the issue. I can't test latest version, as my project is pretty big and conflicts with dependencies. I've setup a clean project, but I'm having other weird issues with the setup, so I can't tell...

**Comment by atif1996** [comment]
I've been having issues getting the cert to read on my M1 macbook pro.  The error I'm getting is different however, see below.  I have confirmed if I store the cert on disk, it works fine.   I can also pull the cert from keyvault and use it in a Confidential Client directly, however, I'm trying to the webapp config as follows and expect it to get the cert from the appsettings.json setup

```
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"))
        .EnableTokenAcquisitionToCallDownstreamApi()
            .AddInMemoryTokenCaches();
```

```
All client certificates passed to the configuration have expired or can't be loaded.  (Parameter 'clientCredentials')
   at Microsoft.Identity.Web.ConfidentialClientApplicationBuilderExtension.WithClientCredentials(ConfidentialClientApplicationBuilder builder, IEnumerable`1 clientCredentials, ILogger logger, ICredentialsLoader credentialsLoader, CredentialSourceLoaderParameters credentialSourceLoaderParameters)
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Program.<<Main>$>g__Handler|0_0(HttpContext httpContext, IDownstreamApi downstreamApi, ITokenAcquisition tokenAcq) in /Users/atifmahmood/ms/exampleWebApiWithCertAuth/Program.cs:line 43
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteTaskOfT>g__ExecuteAwaited|133_0[T](Task`1 task, HttpContext httpContext, JsonTypeInfo`1 jsonTypeInfo)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   ```
   
   I'll try this on a windows VM and see if the results are different.

**Comment by atif1996** [comment]
Just tested this on windows I think we have a Mac bug on the Apple implementation here.  

First config I tried from the example.  Fails on the M1 Mac.
```
                services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(Configuration.GetSection(AzureAdOptions.Section))
                    .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddInMemoryTokenCaches();
```

Then I tried this config.  Also failed on the Mac. 
```
                var certName = Configuration["AzureAd:ClientCredentials:-1:KeyVaultCertificateName"]!;
                services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(
                        configureJwtBearerOptions =>
                        {
                            Configuration.Bind("AzureAd", configureJwtBearerOptions);
                        },
                        microsoftIdentityOptions =>
                        {
                            Configuration.Bind("AzureAd", microsoftIdentityOptions);
                            microsoftIdentityOptions.TokenDecryptionCertificates = new[]
                            {
                                CertificateDescription.FromKeyVault(Configuration["KeyVault:Url"]!, certName),
                            };
                        })
                    .EnableTokenAcquisitionToCallDownstreamApi(options => Configuration.Bind("AzureAd", options))
                    .AddInMemoryTokenCaches();
```

After seeing this post, I tried both implementations on windows, and both get me a valid token to my downstream services.  So it sounds like if your debugging on a Mac, you can't user certs stored in keyvault. What is interesting is that I can read the keyvault secrets in code just fine.  Perhaps if I read the binary and give present the configuration to the library as a base 64 encoded cert it would work?

Would something like this make sense
```
               var certName = Configuration["AzureAd:ClientCredentials:-1:KeyVaultCertificateName"]!;
                var privateKeyBytes = Convert.FromBase64String(Configuration[certName]!);
                var certificate = new X509Certificate2((ReadOnlySpan<byte>)privateKeyBytes, null, X509KeyStorageFlags.MachineKeySet);
                Configuration["AzureAd:ClientCredentials:1:SourceType"] = "Base64Encoded";
                var certBytes = certificate.Export(X509ContentType.Cert);
                var certBase64 = Convert.ToBase64String(certBytes);
                Configuration["AzureAd:ClientCredentials:1:Base64EncodedValue"] = certBase64; // private key
                services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(Configuration.GetSection(AzureAdOptions.Section))
                    .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddInMemoryTokenCaches();
                services.AddTokenAcquisition(true);
```

**Comment by bgavrilMS** [comment]
Setting as P3 since this affects dev environment only, not production.

**Comment by bgavrilMS** [comment]
Ok, so it's not a bug in .NET, it's a known limitation of MacOs, see https://learn.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography#write-a-pkcs12pfx

**Comment by luismanez** [comment]
@bgavrilMS I guessed so. Thanks for the fix. Will test it as soon as I can. Feel free to close the issue if you want.
Cheers.
