### ISSUE TITLE
Deploying Code to Azure App Service changes the returned token format from App Reg to Graph  

### ISSUE THREAD

**Issue by BrianMacD** [AzureAD/microsoft-identity-web#2056]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.25.10

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

Distributed caches

### Description

Hi, 

I have been having a deployment issue of my code to Azure using a Blazor Server App calling a protected Web API.  I have been using the helper: 

 await _downstreamWebApi.CallWebApiForUserAsync(
    "APIServer",
    options =>
    {
        options.HttpMethod = HttpMethod.Get;
        options.RelativePath = endPoint;
    });

This works as expected when the App is running locally (with the API server in Azure). 

When the App is deployed then the token changes radically to a Graph API based one.  

I have no changings in the code. So I guess this is my configuration or something (Not sure)

I have tried using TokenAcwuisition.GetAccessTokenForUserAsync(scopes) which returns the expected token on my local, but when deployed it returns a Graph API token and not my App Registration token.  

This has been driving me a bit nuts over the couple of days. 

Any help would be great.

Configuration :  

builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(builder.Configuration, "AzureAd")
                .EnableTokenAcquisitionToCallDownstreamApi(scopes)
                .AddDownstreamWebApi("APIServer", builder.Configuration.GetSection("APIServer"))
                .AddDistributedTokenCaches();

This in is on .net 7.0.

Regards

Brian

### Reproduction steps

Run code locally - works 
Deploy as an App Service to Azure - Fails 

### Error message

System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.Identity.Web.AppServicesAuthenticationTokenAcquisition.GetEffectiveAuthenticationScheme(String authenticationScheme)
   at Microsoft.Identity.Web.DownstreamWebApi.CallWebApiForUserAsync(String serviceName, String authenticationScheme, Action`1 calledDownstreamWebApiOptionsOverride, ClaimsPrincipal user, StringContent content)
   at GlobillizeApp.API.RemoteCall.GetData[T](String endPoint) in C:\Users\brian\OneDrive\Documents\Globillize\Repo\Globillize\GlobillizeApp\API\RemoteCall.cs:line 36
   at GlobillizeApp.Pages.Billing.Run.OnInitializedAsync() in C:\Users\brian\OneDrive\Documents\Globillize\Repo\Globillize\GlobillizeApp\Pages\Billing\Run.razor:line 34
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

### Relevant code snippets

```csharp
string[] scopes = { _configuration["APIServer:Scopes"] };

            var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(scopes); //Just to trap the access token for inspection.

            HttpResponseMessage value = await _downstreamWebApi.CallWebApiForUserAsync(
                            "APIServer",
                            options =>
                            {
                                options.HttpMethod = HttpMethod.Get;
                                options.RelativePath = endPoint;
                            });

            var returnContents = await value.Content.ReadFromJsonAsync<T>();

            return returnContents ?? new ();
```

### Expected behavior

I would expect when the app is deployed that the same tokens formats are returned.

**Comment by BrianMacD** [comment]
Just an update on this with the tokens returned from Local and Deployed:

Local (as expected):

{
  "aud": "api://d11d3663-a296-47c4-93c0-0fb51e825fbd",
  "iss": "https://sts.windows.net/6e5c4dfd-4a13-44e1-a595-4446330c34f3/",
  "iat": 1674555420,
  "nbf": 1674555420,
  "exp": 1674561023,
  "acr": "1",
  "aio": "ATQAy/8TAAAANASN0+XhXdRcft0gGaUZPduh3w2YPYc5vnr/fVJJNqwAGEAdMCMJ4d+yaPeduHch",
  "amr": [
    "pwd"
  ],
  "appid": "91ea0220-3092-415d-bccf-7b75b721f075",
  "appidacr": "1",
  "ipaddr": "145.224.65.134",
  "name": "Test User1",
  "oid": "36bee037-4a28-417d-9db6-5c7e32dc6829",
  "rh": "0.AU4A_U1cbhNK4USllURGMww082M2HdGWosRHk8APtR6CX72DAH4.",
  "roles": [
    "user.user"
  ],
  "scp": "access_as_user",
  "sub": "mCGFScKmCN35ZPP0XN2jlZ8mA6Wr4Jd_KVmehmfW46I",
  "tid": "6e5c4dfd-4a13-44e1-a595-4446330c34f3",
  "unique_name": "testuser1@globillize.com",
  "upn": "testuser1@globillize.com",
  "uti": "-IkUiCPNT0SyFECaKKE-AA",
  "ver": "1.0"
}
Signature Valid

From App Server (Deployed with no code/configuration changes ):
 {
  "aud": "00000003-0000-0000-c000-000000000000",
  "iss": "https://sts.windows.net/6e5c4dfd-4a13-44e1-a595-4446330c34f3/",
  "iat": 1674555684,
  "nbf": 1674555684,
  "exp": 1674560862,
  "acct": 0,
  "acr": "1",
  "aio": "ATQAy/8TAAAAES344EA4FF7gqTxfVYtHMxEmr89EfFLU4pQ5A0TofruKuVOd9JDi0K4Ros7M4bXV",
  "amr": [
    "pwd"
  ],
  "app_displayname": "GlobillizeApp",
  "appid": "91ea0220-3092-415d-bccf-7b75b721f075",
  "appidacr": "1",
  "idtyp": "user",
  "ipaddr": "145.224.65.134",
  "name": "Test User1",
  "oid": "36bee037-4a28-417d-9db6-5c7e32dc6829",
  "platf": "3",
  "puid": "100320026B82C2CF",
  "rh": "0.AU4A_U1cbhNK4USllURGMww08wMAAAAAAAAAwAAAAAAAAACDAH4.",
  "scp": "openid profile email",
  "sub": "5GP654vzY5rBiMaRiqgQQmVbyNS2S0Qq5E9hvVMUpcI",
  "tenant_region_scope": "EU",
  "tid": "6e5c4dfd-4a13-44e1-a595-4446330c34f3",
  "unique_name": "testuser1@globillize.com",
  "upn": "testuser1@globillize.com",
  "uti": "-yieXszICkCGeYD3dXYXAA",
  "ver": "1.0",
  "wids": [
    "b79fbf4d-3ef9-4689-8143-76b194e85509"
  ],
  "xms_st": {
    "sub": "ZXSQcgaLIesURECrWF9HA3gK05K2t_MqmMwkbXcHJzg"
  },
  "xms_tcdt": 1672843721
}
Signature invalid

Any ideas why the difference from the same code?

Regards

**Comment by schwammy** [comment]
I'm dealing with the same issue. Any luck figuring it out?

**Comment by BriMacD2000** [comment]
Yep.  Fixed it looks like it was the way I configured it in the Program.cs:

builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
		.AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"))
        .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
		.AddMicrosoftGraph(builder.Configuration.GetSection("MicrosoftGraph"))
        .AddDistributedTokenCaches()
        .AddDownstreamWebApi("DownstreamApi",builder.Configuration.GetSection("DownstreamApi"))
		.AddDistributedTokenCaches()
        .AddDownstreamWebApi("DownstreamOutput", builder.Configuration.GetSection("DownstreamOutput"))
        .AddDistributedTokenCaches();

builder.Services.AddDistributedSqlServerCache(options =>
{
    options.ConnectionString = builder.Configuration.GetConnectionString("Db");
    options.SchemaName = "dbo";
    options.TableName = "tablecache";

    options.DefaultSlidingExpiration = TimeSpan.FromMinutes(90);
});

**Comment by BriMacD2000** [comment]
Just make sure the initial scopes cover everything:

var initialScopes = builder.Configuration["DownstreamOutput:Scopes"]?.Split(' ') ?? builder.Configuration["DownstreamApi:Scopes"]?.Split(' ') ?? builder.Configuration["MicrosoftGraph:Scopes"]?.Split(' ');

**Comment by schwammy** [comment]
Thanks. It isn't working for me, I think it might be something unrelated because all of the demos seem to work fine.
