### ISSUE TITLE
Fails to get claims from user info endpoint - with a new Scope 

### ISSUE THREAD

**Issue by markharrison** [AzureAD/microsoft-identity-web#2081]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.25.0

### Web app

Sign-in users and call web APIs

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

I had my auth logic working until I added a new Scope .
It now fails get to claims from user info endpoint - the log shows 401 Unauthorized

thx

### Reproduction steps

Auth working fine til I added a new scope to my App Registration.

It works fine if I set options.GetClaimsFromUserInfoEndpoint = false  ... but I then dont get all the claims for the user 

### Id Web logs

```
Program: Information: OnRedirectToIdentityProviderFunc
The thread 0x91b0 has exited with code 0 (0x0).
The thread 0x8e68 has exited with code 0 (0x0).
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Dev\IdentityWeb\bin\Debug\net7.0\Microsoft.IdentityModel.JsonWebTokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Program: Information: OnTokenValidatedFunc
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Error: Exception occurred while processing message.

System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.GetUserInformationAsync(OpenIdConnectMessage message, JwtSecurityToken jwt, ClaimsPrincipal principal, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Web.HttpUtility.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Program: Information: OnAuthenticationFailedFunc

```

### Relevant code snippets

```csharp
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
      .AddMicrosoftIdentityWebApp(options =>
      {
          builder.Configuration.Bind("AzureAD", options);
          options.ResponseType = OpenIdConnectResponseType.Code;
          options.Events ??= new OpenIdConnectEvents();
          options.Events.OnTokenValidated += OnTokenValidatedFunc;
          options.Events.OnAuthenticationFailed += OnAuthenticationFailedFunc;
          options.Events.OnAccessDenied += OnAccessDeniedFunc;
          options.Events.OnRemoteFailure += OnRemoteFailureFunc;
          options.Events.OnUserInformationReceived += OnUserInformationReceivedFunc;
          options.Events.OnRedirectToIdentityProvider += OnRedirectToIdentityProviderFunc;
          options.Events.OnTicketReceived += OnTicketReceivedFunc;
          options.SaveTokens = true;
          options.UsePkce = true;
          options.GetClaimsFromUserInfoEndpoint = true ;
          options.Scope.Add("api://e8b9cef4-b6e6-41de-828e-8f31ad0aa15d/Red.read");
```
```


### Regression

_No response_

### Expected behavior

authenticated user with all claims retrieved .

**Comment by markharrison** [comment]
Looking at my access token - which I assume is used to call the user endpoint 

```
access_token: {
"typ":"JWT",
"alg":"RS256",
"x5t":"-KI3Q9nNR7bRofxmeZoXqbHZGew",
"kid":"-KI3Q9nNR7bRofxmeZoXqbHZGew"
}.{
"aud":"api://e8b9cef4-b6e6-41de-828e-8f31ad0aa15d",

<snipped>
 
"scp":"Red.read",

<snipped>

}
```

shouldnt the scope include openid  profile, email?

if i take out my new 'api' scope - the access token is 

```
"scp":"openid profile User.Read email",
```

**Comment by markharrison** [comment]
if i set my code to 

```
          options.GetClaimsFromUserInfoEndpoint = true;
          options.Scope.Add("User.Read");
          options.Scope.Add("api://e8b9cef4-b6e6-41de-828e-8f31ad0aa15d/Red.read");
```

then the access token includes 

```
"scp":"openid profile User.Read email",
```

and the options.GetClaimsFromUserInfoEndpoint = true ; works 

but I no longer have my APi scope in the access token

**Comment by markharrison** [comment]
This now works as expected in v 2.5.
