### ISSUE TITLE
Microsoft.Identity.Web with Docker on App Service - redirect url mismatch

### ISSUE THREAD

**Issue by markharrison** [AzureAD/microsoft-identity-web#2102]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.5

### Web app

Sign-in users

### Web API

Not Applicable

### Token cache serialization

In-memory caches

### Description

Error - auth fail - to do with Redirect urls.   

I have done the forward headers - is there anymore I need to do ?

I can see https is in the redirect url to the original logon request 

```
https://login.microsoftonline.com/xxxxx-9b08-4844-a7c2-2467d637847b/oauth2/v2.0/authorize?client_id=xxxx-16e9-4882-81e0-18d4e1a1479b&redirect_uri=https%3a%2f%2fmarkidentityweb.azur
```

### Reproduction steps

using Docker and Azure App Service (Linux)

### Error message

A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details. Original exception: AADSTS500112: The reply address 'http://markidentityweb.azurewebsites.net/signin-oidc' does not match the reply address 'https://markidentityweb.azurewebsites.net/signin-oidc' provided when requesting Authorization code. Trace ID: 7a52c0b8-6996-470c-98cc-44ef3edc7c00 Correlation ID: 56f3887b-ff1c-4872-bea3-a695032ccc66 Timestamp: 2023-03-06 23:15:15Z

### Relevant code snippets

```csharp
#
var forwardOptions = new ForwardedHeadersOptions
{
    ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedFor |
                       Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedProto,
    RequireHeaderSymmetry = false
};
forwardOptions.KnownNetworks.Clear();
forwardOptions.KnownProxies.Clear();
app.UseForwardedHeaders(forwardOptions);

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();
app.MapRazorPages();
app.MapControllers();
app.Run();
```

### Expected behavior

successful login

**Comment by markharrison** [comment]
i see this in the logs 

```
2023-03-06T23:50:37.007023120Z fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[17]
2023-03-06T23:50:37.007026620Z       Exception occurred while processing message.
2023-03-06T23:50:37.007029920Z       MSAL.NetCore.4.48.1.0.MsalServiceException: 
2023-03-06T23:50:37.007033120Z       	ErrorCode: invalid_client

2023-03-06T23:50:37.007036420Z       Microsoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS500112: The reply address 'http://markidentityweb.azurewebsites.net/signin-oidc' does not match the reply address 'https://markidentityweb.azurewebsites.net/signin-oidc' provided when requesting Authorization code.

2023-03-06T23:50:37.007040720Z       Trace ID: b52a8b18-5c7a-410f-88b6-15acdf424900
2023-03-06T23:50:37.007044320Z       Correlation ID: bddae54b-9e95-40df-83c4-7f3c2ffb6911
2023-03-06T23:50:37.007047820Z       Timestamp: 2023-03-06 23:50:36Z
2023-03-06T23:50:37.007068220Z          at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
2023-03-06T23:50:37.007072620Z          at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
2023-03-06T23:50:37.007076020Z          at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
2023-03-06T23:50:37.007079920Z          at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders, Func`2 onBeforePostRequestHandler)
2023-03-06T23:50:37.007083720Z          at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
2023-03-06T23:50:37.007087120Z          at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
2023-03-06T23:50:37.007090521Z          at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
2023-03-06T23:50:37.007097421Z          at Microsoft.Identity.Client.Internal.Requests.ConfidentialAuthCodeRequest.ExecuteAsync(CancellationToken cancellationToken)
2023-03-06T23:50:37.007100921Z          at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
2023-03-06T23:50:37.007104421Z          at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByAuthorizationCodeParameters authorizationCodeParameters, CancellationToken cancellationToken)
2023-03-06T23:50:37.007108021Z          at Microsoft.Identity.Web.TokenAcquisition.AddAccountToCacheFromAuthorizationCodeAsync(AuthCodeRedemptionParameters authCodeRedemptionParameters)
2023-03-06T23:50:37.007111821Z          at Microsoft.Identity.Web.TokenAcquisitionAspNetCore.AddAccountToCacheFromAuthorizationCodeAsync(AuthorizationCodeReceivedContext context, IEnumerable`1 scopes, String authenticationScheme)
2023-03-06T23:50:37.007115621Z          at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder.<>c__DisplayClass11_1.<<WebAppCallsWebApiImplementation>b__1>d.MoveNext()
2023-03-06T23:50:37.007120121Z       --- End of stack trace from previous location ---
2023-03-06T23:50:37.007123621Z          at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RunAuthorizationCodeReceivedEventAsync(OpenIdConnectMessage authorizationResponse, ClaimsPrincipal user, AuthenticationProperties properties, JwtSecurityToken jwt)
2023-03-06T23:50:37.007127321Z          at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()

2023-03-06T23:50:37.007130821Z       	StatusCode: 400 
2023-03-06T23:50:37.007145121Z       	ResponseBody: {"error":"invalid_client","error_description":"AADSTS500112: The reply address 'http://markidentityweb.azurewebsites.net/signin-oidc' does not match the reply address 'https://markidentityweb.azurewebsites.net/signin-oidc' provided when requesting Authorization code.\r\nTrace ID: b52a8b18-5c7a-410f-88b6-15acdf424900\r\nCorrelation ID: bddae54b-9e95-40df-83c4-7f3c2ffb6911\r\nTimestamp: 2023-03-06 23:50:36Z","error_codes":[500112],"timestamp":"2023-03-06 23:50:36Z","trace_id":"b52a8b18-5c7a-410f-88b6-15acdf424900","correlation_id":"bddae54b-9e95-40df-83c4-7f3c2ffb6911"} 

2023-03-06T23:50:37.007151321Z       	Headers: Cache-Control: no-store, no-cache
2023-03-06T23:50:37.007154921Z       Pragma: no-cache
2023-03-06T23:50:37.007158321Z       Strict-Transport-Security: max-age=31536000; includeSubDomains
2023-03-06T23:50:37.007161921Z       X-Content-Type-Options: nosniff
2023-03-06T23:50:37.007165321Z       P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
2023-03-06T23:50:37.007178922Z       client-request-id: bddae54b-9e95-40df-83c4-7f3c2ffb6911
2023-03-06T23:50:37.007183022Z       x-ms-request-id: b52a8b18-5c7a-410f-88b6-15acdf424900
2023-03-06T23:50:37.007186522Z       x-ms-ests-server: 2.1.14711.7 - SCUS ProdSlices
```

**Comment by jmprieur** [comment]
@markharrison, did you see this? 
https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers

**Comment by markharrison** [comment]
thanks @jmprieur - yes I read that and have implemented the ```UseForwardedHeaders``` functionality.  This alone does not seem enough.  ( Im using .NET 7.0 )

**Comment by michiproep** [comment]
Hi @markharrison,
I was facing a similar issue. I think, the ForwardedHeader-Middleware behaves strange. I tryed to debug the middleware but it's kind of hard to do. Anyway, when I just set 
ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedProto
it seemed to work.
Actually, I wanted to use ForwardedHeaders.All but this broke the app. It never set the scheme to https

**Comment by markharrison** [comment]
ive added some diagnostics into the hook ```RedirectToIdentityProviderFunc``` and inspect ```ctx.ProtocolMessage.RedirectUri```

This has the correct URL with "https" 

Its somewhere after here that the mismatch is being raised.

**Comment by markharrison** [comment]
I have it working 😀

After trying numerous things I stumbled across an article that mentions creating an env variable 
```"ASPNETCORE_FORWARDEDHEADERS_ENABLED"=true```

With this env variable it worked!
I have stripped out all the UseForwardedHeaders code - and it still works as long as the the env variable is set.

@jmprieur - maybe worth something in that Wiki page ?

**Comment by michiproep** [comment]
is this just for the deployed version on azure or even on local dev environment?

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Mark Harrison ***@***.***>
Gesendet: Tuesday, March 7, 2023 6:30:59 PM
An: AzureAD/microsoft-identity-web ***@***.***>
Cc: Michael Pröpster ***@***.***>; Comment ***@***.***>
Betreff: Re: [AzureAD/microsoft-identity-web] Microsoft.Identity.Web with Docker on App Service - redirect url mismatch (Issue #2102)


I have it working 😀

After trying numerous things I stumbled across an article that mentions creating an env variable
"ASPNETCORE_FORWARDEDHEADERS_ENABLED"=true

With this env variable it worked!
I have stripped out all the UseForwardedHeaders code - and it still works as long as the the env variable is set.

@jmprieur<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjmprieur&data=05%7C01%7C%7Cff9f0547b29f45cdfb9d08db1f31b7cb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638138070613012123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yjunMCRgR3GEpLiiD6tL1sknnDRAnrxGvANRte0zRUs%3D&reserved=0> - maybe worth something in that Wiki page ?

**Comment by markharrison** [comment]
>>is this just for the deployed version on azure or even on local dev environment?
At this moment - just in Azure App Service (linux container).
Locally ive only tested on IISExpress - no containers.

**Comment by markharrison** [comment]
@michiproep  
Update - just tested using Docker Desktop locally - and I did not need to set the ```ASPNETCORE_FORWARDEDHEADERS_ENABLED``` env variable for it to work.  So its just needed for Azure AppService .

**Comment by jmprieur** [comment]
> @jmprieur - maybe worth adding something in that Wiki page ?

Thanks @markharrison for sharing the solution./
I've updated the wiki page: https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-web-apps-to-App-Services-as-Linux-containers#how-to-fix-it
cc: @jennyf19 

closing this issue (answered).
