### ISSUE TITLE
Clarify support for Client Credentials Flow with Azure AD B2C

### ISSUE THREAD

**Issue by codeminic** [AzureAD/microsoft-identity-web#2106]
### Documentation related to component
Azure AD B2C Limitations (https://github.com/AzureAD/microsoft-identity-web/wiki/b2c-limitations#you-cannot-use-itokenacquisitiongettokenforappasync-or-idownstreamapicallwebapiforappasync-in-azure-ad-b2c-web-apps)

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
The [documentation that lists Azure AD B2C limitations](https://github.com/AzureAD/microsoft-identity-web/wiki/b2c-limitations#you-cannot-use-itokenacquisitiongettokenforappasync-or-idownstreamapicallwebapiforappasync-in-azure-ad-b2c-web-apps) states that one cannot use `ITokenAcquisition.GetTokenForAppAsync` with AD B2C, because AD B2C does not support the client credentials flow. 

The docs from AD B2C however has a [page dedicated to the usage with client credentials flow](https://learn.microsoft.com/en-us/azure/active-directory-b2c/client-credentials-grant-flow?pivots=b2c-user-flow#step-3-obtain-an-access-token) and how to get an access token with `curl`.

Is the documentation outdated or is the Client Credentials Flow not supported using `Microsoft.Identity.Web`? 
I tried to integrate it into an application, but did not get it working, and ended up writing the code to get an access token myself. Would be really cool to get support for this!

Thank you for clarifying!

**Comment by jmprieur** [comment]
Thanks @codeminic 
Thanks for the heads-up. We'll fix our wiki if B2C now supports client credentials. Id.Web does not provide any limitation there, so if the B2C service supports the flow, Id.Web will support it.

Did you try GetTokenForAppAsync between 2 b2c apps?

**Comment by jmprieur** [comment]
Thanks @codeminic 
we fixed the wiki!

**Comment by codeminic** [comment]
@jmprieur thanks for following up!

> Did you try GetTokenForAppAsync between 2 b2c apps?
Yes! I created a little repro here: https://github.com/codeminic/B2C-Client-Credentials-Flow. It's just two minimal API's, API A is unprotected and calls API B (which is protected).

When calling `GetTokenForAppAsync`, I get the following exception:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'tenantId')
   at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1.WithTenantId(String tenantId)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in C:\Users\domin\Projects\SPL\B2C-Client-Credentials-Flow\ApiA\Program.cs:line 27
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

When I specify the TenantId in `GetTokenForAppAsync`, I get another exception:
```
Microsoft.Identity.Client.MsalClientException: WithTenantId can only be used when an AAD authority is specified at the application level.
   at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1.WithTenantId(String tenantId)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in C:\Users\domin\Projects\SPL\B2C-Client-Credentials-Flow\ApiA\Program.cs:line 27
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
So.. i set "Authority" in the appsettings, but that did not help - still got the same exception. 

Is there some other B2C-specific setup that I missed?

Thank you for your help!
