### ISSUE TITLE
Deployed Asp .Net core mvc web app gets unauthorized error when calling deployed web API.

### ISSUE THREAD

**Issue by HHOSSAIN** [AzureAD/microsoft-identity-web#2107]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.24.1

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

I created Asp .net web api which uses Microsoft Identity Platform as its authentication type and has only 1 scope- "Scopes": "access_as_user". I also created an Asp .net core mvc web app which also uses Microsoft Identity Platform as its authentication type aimed to make calls to the secure web api. Now, when I run the app locally and call the deployed version of the web Api, it is able to make successful calls to the api and fetch data. However, when I deploy the web app and try to call the deployed secure web Api from there, I get Internal Server Error 401 (unauthorized).
I have created the app registrations in azure for both the web app and web api and also both of them were deployed to azure app service in the same tenant. My possible guesses for the error was not specifying the redirect URIs for the deployed web app. So, I added these 2 redirect URIs for my web app-
1)https://apicallapp2.azurewebsites.net/signin-oidc
2)http://localhost:5068/signin-oidc
I also added the api in the API permissions as shown in the picture-
<img width="130" alt="image" src="https://user-images.githubusercontent.com/59385182/224234498-6acbd7b2-fae0-4620-afaa-9cc0617acd95.png">
For the deployed web app, I also added Microsoft as Identity Provider in app services, so it allows me to sign in to the app successfully in its deployed version but I get the unauthorized error when calling the deployed web Api. The point to note is when I run the same web app locally and try to call the "deployed" web Api using it, it is able to make successful calls to the API.
Below are some code snippets from my api and web app:
API:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/59385182/224235859-5bcbb926-bb8c-4961-aa8e-a4c939f36dd7.png">
<img width="505" alt="image" src="https://user-images.githubusercontent.com/59385182/224235938-f4c160d6-357d-4042-b3af-e8000c90ae9b.png">
Web App:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/59385182/224236285-8cee2287-6e4a-4ee7-a48e-d4fe50d1732c.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/59385182/224237169-b6a0a31f-16f1-49be-932c-b87b45702a7d.png">

### Reproduction steps

Try visiting this link which will give you error- https://apicallapp2.azurewebsites.net/Home/PersonalApiCall

### Error message

System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at ApiCallApp2.Controllers.HomeController.PersonalApiCall() in C:\Users\hasne.hossain\source\repos\ApiCallApp2\ApiCallApp2\Controllers\HomeController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Relevant code snippets

```csharp
API:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/59385182/224235859-5bcbb926-bb8c-4961-aa8e-a4c939f36dd7.png">
<img width="505" alt="image" src="https://user-images.githubusercontent.com/59385182/224235938-f4c160d6-357d-4042-b3af-e8000c90ae9b.png">
Web App:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/59385182/224236285-8cee2287-6e4a-4ee7-a48e-d4fe50d1732c.png">
```

### Expected behavior

I expect it to return the weather data-
[{"date":"2023-03-11T06:07:52.3777938+00:00","temperatureC":25,"temperatureF":76,"summary":"Balmy"},{"date":"2023-03-12T06:07:52.3780347+00:00","temperatureC":11,"temperatureF":51,"summary":"Scorching"},{"date":"2023-03-13T06:07:52.3780379+00:00","temperatureC":4,"temperatureF":39,"summary":"Chilly"},{"date":"2023-03-14T06:07:52.3780382+00:00","temperatureC":47,"temperatureF":116,"summary":"Scorching"},{"date":"2023-03-15T06:07:52.3780384+00:00","temperatureC":12,"temperatureF":53,"summary":"Sweltering"}]

**Comment by jmprieur** [comment]
@HHOSSAIN 
If you have protected your web app with Microsoft.Identity.Web (and you have since that works locally), I would recommend you **don't** use App services authentication, which itself another auth layer and disables Id.Web's auth.

If you use App services authentication, you would have to tell to use that app registration. See https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=azure-resource-explorer, which is to call Microsoft Graph, but that you can adapt to use your own web API.

**Comment by jmprieur** [comment]
@HHOSSAIN closing as I believe this is answered
feel free to reopen if you disagree

**Comment by HHOSSAIN** [comment]
> @HHOSSAIN If you have protected your web app with Microsoft.Identity.Web (and you have since that works locally), I would recommend you **don't** use App services authentication, which itself another auth layer and disables Id.Web's auth.
> 
> If you use App services authentication, you would have to tell to use that app registration. See https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=azure-resource-explorer, which is to call Microsoft Graph, but that you can adapt to use your own web API.

@jmprieur I am a bit unsure of what you meant by removing App services authentication. I get this "MsalClientException: One client credential type required either: ..." error when I removed App services authentication for my mvc web app(called ApiCallApp2) as shown in the screenshot below.
<img width="928" alt="image" src="https://user-images.githubusercontent.com/59385182/229644002-b1f90879-8924-4120-ad2b-df090f86e6eb.png">

I tried removing Identity Provider from App Service for the web app and that now prevents me to sign in to the deployed web app itself.
![image](https://user-images.githubusercontent.com/59385182/229644229-03af3f2d-2055-435d-9632-bed3cf91da29.png)
