### ISSUE TITLE
Logout failure on a multi-tenanted application

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#2184]
My application supports multiple customers. Users identify their customer identity by adding "tenant" parameter on the URL, e.g., "https://xxxxx?tenant=TenantOne". Multiple tenants are configured in appsettings.json:

![image](https://user-images.githubusercontent.com/4291622/230427025-d53b179a-2961-4eea-8a3d-514b48fb852c.png)

The OIDC scheme and Cookie scheme are built out of the section name in appsettings.json for the configured tenants:
```
            foreach (var section in _configuration.GetChildren())
            {
                var options = new MicrosoftIdentityOptions();
                section.Bind(options);

                if (options.Instance.IsNullOrEmpty() || options.ClientId.IsNullOrEmpty())
                    continue; // Skip sections that are not defining tenants

                // AuthorizationPolicyProvider determines the scheme for incoming request at runtime that matches the scheme name here.
                var (openIdConnectScheme, cookieScheme) = DetermineSchemes(section.Key);

                services.AddAuthentication()
                    .AddMicrosoftIdentityWebApp(
                        identityOptions => section.Bind(identityOptions),
                        cookieOptions =>
                        {
                            var tenantElement = _appConfiguration.Tenants.FirstOrDefault(x => x.TenantId.Equals(options.TenantId, StringComparison.CurrentCultureIgnoreCase));
                            cookieOptions.Cookie.Name = ".AspNetCore.Cookies";
                            cookieOptions.Cookie.MaxAge = TimeSpan.FromHours(tenantElement?.CookieMaxAgeHours ?? Constants.DefaultCookieMaxAgeHours);
                        },
                        openIdConnectScheme, cookieScheme)
                    .EnableTokenAcquisitionToCallDownstreamApi() // These steps enable "authorization code flow".
                    .AddMyTokenCache(cacheOptions => cacheOptions.Ttl= TimeSpan.FromDays(_appConfiguration.TokenCacheExpiryDays));
            }
```
```
        private static (string openIdConnectScheme, string cookieScheme) DetermineSchemes(string sectionKey)
        {
            return (sectionKey, $"{sectionKey}{CookieAuthenticationDefaults.AuthenticationScheme}");
        }
```
I used a custom authorization policy provider to ensure that correct scheme is used for a given tenant:
```
    public class AuthorizationPolicyProvider : IAuthorizationPolicyProvider
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private ConcurrentDictionary<string, AuthorizationPolicy> _policyCache = new ();

        public AuthorizationPolicyProvider(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        Task<AuthorizationPolicy> IAuthorizationPolicyProvider.GetDefaultPolicyAsync()
        {
            return Task.FromResult(GetPolicy());
        }

        Task<AuthorizationPolicy> IAuthorizationPolicyProvider.GetFallbackPolicyAsync()
        {
            return Task.FromResult(GetPolicy());
        }

        Task<AuthorizationPolicy> IAuthorizationPolicyProvider.GetPolicyAsync(string policyName)
        {
            throw new NotImplementedException();
        }

        private AuthorizationPolicy GetPolicy()
        {
            var httpContext = _httpContextAccessor.HttpContext;
            var schemeName = httpContext?.Request.GetTenant();

            return _policyCache.GetOrAdd(schemeName, 
                _ => new AuthorizationPolicyBuilder()
                    .AddRequirements(new AssertionRequirement(_ => true)) // Policy must have at least one requirement
                    .AddAuthenticationSchemes(schemeName)
                    .Build());
        }
    }
```

It works great for logins. However I ran into an issue with logouts.

The Logout operation on my app simply redirects the call to "MicrosoftIdentity/Account/SignOut" as below:
```
        [HttpGet]
        public RedirectResult Logout()
        {
            var tenant = Request.GetTenant();
            return Redirect($"/{Constants.UrlRoot}/MicrosoftIdentity/Account/SignOut?tenant={tenant}");
        }
```
The Logout operation fails with the following exception:
```
System.InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured ExceptionHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.
   at async Task Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at async Task Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)+Awaited(?)
   at async Task Microsoft.AspNetCore.Server.HttpSys.RequestContext<TContext>.ExecuteAsync() x 2 ---> System.InvalidOperationException: No sign-out authentication handler is registered for the scheme 'Cookies'. The registered sign-out schemes are: AzureAdCookies, AzureAd, TenantOneCookies, TenantOne, TenantTwoCookies, TenantTwo. Did you forget to call AddAuthentication().AddCookie("Cookies",...)?
   at async Task Microsoft.AspNetCore.Authentication.AuthenticationService.SignOutAsync(HttpContext context, string scheme, AuthenticationProperties properties)
   at async Task Microsoft.AspNetCore.Mvc.SignOutResult.ExecuteAsync(HttpContext httpContext)
   at async Task Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync<TFilter, TFilterAsync>()+Awaited(?)
   at void Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Task Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
   at Task Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
   at async Task Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()+Awaited(?)
   at void Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Task Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
   at Task Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   at async Task Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()+Logged(?) x 2
   at async Task Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)+AwaitRequestTask(?)
   at async Task Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at async Task Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

I tried following the suggestion in the exception above to call "AddAuthentication().AddCookie()", but my app fails with exception stating that "Cookies" scheme already exists.
```
Unhandled exception. System.InvalidOperationException: Scheme already exists: Cookies
   at Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(String name, Action`1 configureBuilder)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__0(AuthenticationOptions o)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions`1 options, IDictionary`2 schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

I am looking for advice how to get around "No sign-out authentication handler is registered for the scheme 'Cookies'" error. Thanks in advance.

**Comment by WenningQiu** [comment]
Hmm, looks like `Account/SignOut` is using the default schemes.

```
        /// <summary>
        /// Handles the user sign-out.
        /// </summary>
        /// <param name="scheme">Authentication scheme.</param>
        /// <returns>Sign out result.</returns>
        [HttpGet("{scheme?}")]
        public IActionResult SignOut(
            [FromRoute] string scheme)
        {
            if (AppServicesAuthenticationInformation.IsAppServicesAadAuthenticationEnabled)
            {
                return LocalRedirect(AppServicesAuthenticationInformation.LogoutUrl);
            }
            else
            {
                scheme ??= OpenIdConnectDefaults.AuthenticationScheme;
                var callbackUrl = Url.Page("/Account/SignedOut", pageHandler: null, values: null, protocol: Request.Scheme);
                return SignOut(
                     new AuthenticationProperties
                     {
                         RedirectUri = callbackUrl,
                     },
                     CookieAuthenticationDefaults.AuthenticationScheme,
                     scheme);
            }
        }
```

**Comment by WenningQiu** [comment]
So I modeled after `Account/SignOut` have created my logout method as below:
```
        [HttpGet]
        public IActionResult Logout()
        {
            var tenant = Request.GetTenant();
            var (oidcScheme, cookieScheme) = tenant.BuildSchemesForTenant();
            var callbackUrl = $"{Request.Scheme}://{Request.Host}/{Constants.UrlRoot}/Azure/LoggedOut?tenant={tenant}";

            return SignOut(new AuthenticationProperties { RedirectUri = callbackUrl }, cookieScheme, oidcScheme);
        }
```
It works great when there is only one tenant in `appsettings.json` (one oidc scheme and one cookie scheme registered). However if there are more than one tenants declared in `appsettings.json` (multiple oidc schemes and multiple cookie schemes registered), it will stop at calling IDP's SignedOutCallbackPath without redirecting to the RedirectUri  provided to the SignOut() call.

![image](https://user-images.githubusercontent.com/4291622/230633278-d1af1e09-cdac-423e-b41b-38a69d7a136c.png)

It turned out that an exception was raised when unprotecting the Signout response message on the line in red box:

![image](https://user-images.githubusercontent.com/4291622/230633576-715d01b0-7b53-4d55-9e7c-723f392b8035.png)

This is the exception detail:
![image](https://user-images.githubusercontent.com/4291622/230633928-f8a8c2ae-820a-4c20-bbb2-5a383b07766c.png)

Am I doing something wrong here?

**Comment by WenningQiu** [comment]
The root cause is the extra spaces in the `SignedOutCallbackPath` key in `appsettings.json` file, which causes the configured callback path to not load correctly. The result is multiple tenants use the default callback and response message gets dispatched to the wrong handler.

**Comment by jmprieur** [comment]
Thanks @WenningQiu for raising this, your investigation and for sharing the root cause
We've proposed PRs to fix the samples: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/685

cc: @jennyf19 @westin-m @derisen

**Comment by WenningQiu** [comment]
@jmprieur Thanks, yes that's where the bad configuration came from.
