### ISSUE TITLE
[Documentation] credentials can be expired despite being logged in, which results in IDW10501 and IDW1010 errors

### ISSUE THREAD

**Issue by kellyyangsong** [AzureAD/microsoft-identity-web#2247]
### Documentation related to component
Calling a downstream API

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [x] needs an example

### Description of the issue
You can be logged into Visual Studio, but with expired credentials. You won't know until you click "account settings" in VS: 
![image](https://github.com/AzureAD/microsoft-identity-web/assets/69649063/bb65832c-f765-4f32-88d7-796b1827124c)

Error returned by IDWeb: 
```
Error: info: Microsoft.Identity.Web.TokenAcquisition[300]
      [MsIdWeb] An error occured during token acquisition: IDW10501: Exception acquiring token for a confidential client.
      System.ArgumentException: IDW10109: All client certificates passed to the configuration have expired or can't be loaded.  (Parameter 'clientCredentials')
         at Microsoft.Identity.Web.ConfidentialClientApplicationBuilderExtension.WithClientCredentials(ConfidentialClientApplicationBuilder builder, IEnumerable`1 clientCredentials, ILogger logger, ICredentialsLoader credentialsLoader, CredentialSourceLoaderParameters credentialSourceLoaderParameters)
         at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
```

This behavior can be documented for easier debugging.

**Comment by kellyyangsong** [comment]
Added new troubleshooting section to [Certificates Wiki](https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates#troubleshooting).
