### ISSUE TITLE
AuthenticationProvider is empty when used with Application permissions and paging (NextPageRequest)

### ISSUE THREAD

**Issue by Jan1503** [AzureAD/microsoft-identity-web#2272]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.Graph

### Microsoft.Identity.Web version

2.11.1

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

I have a strange issue that's buggin me the whole day and I could swear it works last week without any code modifications :)

I have a simple web-api which calls the graph with some delegated permissions without any problems. But there is just one call where I need to get data from the Entitlement Management where the user has no permissions to do, so I use the following with ".WithAppOnly()" which worked till last week:

```cs
public async Task<List<AccessPackageAssignmentPolicy>> GetAccessPackageAssignmentPoliciesAsync(
        CancellationToken cancellationToken = default)
    {
        IEntitlementManagementAssignmentPoliciesCollectionPage? entitlementPolicies = null;
        var accessPackagePolicies = new List<AccessPackageAssignmentPolicy>();
        
        while (entitlementPolicies is not { NextPageRequest: null })
        {
            var entitlementPoliciesRequest = entitlementPolicies?.NextPageRequest ?? _graphServiceClient
                .IdentityGovernance
                .EntitlementManagement
                .AssignmentPolicies
                .Request()
                .Expand("accessPackage")
                .WithAppOnly()
                .Top(999);

            entitlementPolicies = await entitlementPoliciesRequest
                .GetAsync(cancellationToken);

            accessPackagePolicies.AddRange(entitlementPolicies);
        }

        return accessPackagePolicies;
    }
```

Now all of a sudden this throws an MsalUiRequiredException and it took me hours to get closer to the underlying issue:

As you can see in the error message, the first call to the graph uses App-Permission but any subsequent calls DO NOT.

Till this week we don't have more than 100 Assignment Policies in place so the NextPageRequest was null and the error does not occur but now, as we have more than 100 the `NextPageRequest` is populated but does not include the needed `AuthenticationProviderOption`. So any subsequent call will fail with MsalUiRequiredException.

First request is correct:
![image](https://github.com/AzureAD/microsoft-identity-web/assets/10504259/31754d04-3fcc-478b-ab44-19a6c2ad6c01)

Subsequent request does not include the needed `AuthenticationProviderOption`:
![image](https://github.com/AzureAD/microsoft-identity-web/assets/10504259/27ae8991-6ab5-425f-a439-2d1504f9f872)

This looks like a bug to me and I need to implement a workaround until this is fixed.

### Reproduction steps

Create a sample web-api project, add some graph app-permissions and call them with ".WithAppOnly()".
Make sure the result is paged so `NextPageRequest` is populated.
It will fail with MsalUiRequiredException because the second call happens with delegated permissions.

### Error message

```
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:46Z] 
=== Request Data ===
Authority Provided? - True
Scopes - https://graph.microsoft.com/.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 00000000-0000-0000-0000-000000000000
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:46Z] === Token Acquisition (ClientCredentialRequest) started:
	 Scopes: https://graph.microsoft.com/.default
	Authority Host: login.microsoftonline.com
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:46Z] [Internal cache] Total number of cache partitions found while getting access tokens: 0
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:46Z] [FindAccessTokenAsync] Discovered 0 access tokens in cache using partition key: a6fa5e66-3fc5-4f25-989d-47b827636ec1_<tenantID>_AppTokenCache
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:46Z] [Instance Discovery] Instance discovery is enabled and will be performed
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:46Z] [Region discovery] Not using a regional authority. 
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:46Z] Fetching instance discovery from the network from host login.microsoftonline.com. 
System.Net.Http.HttpClient.Default.LogicalHandler: Information: Start processing HTTP request GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2F<tenantID>%2Foauth2%2Fv2.0%2Fauthorize
System.Net.Http.HttpClient.Default.ClientHandler: Information: Sending HTTP request GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2F<tenantID>%2Foauth2%2Fv2.0%2Fauthorize
System.Net.Http.HttpClient.Default.ClientHandler: Information: Received HTTP response headers after 253.9435ms - 200
System.Net.Http.HttpClient.Default.LogicalHandler: Information: End processing HTTP request after 269.6762ms - 200
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] Authority validation enabled? True. 
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] Authority validation - is known env? True. 
System.Net.Http.HttpClient.Default.LogicalHandler: Information: Start processing HTTP request POST https://login.microsoftonline.com/<tenantID>/oauth2/v2.0/token
System.Net.Http.HttpClient.Default.ClientHandler: Information: Sending HTTP request POST https://login.microsoftonline.com/<tenantID>/oauth2/v2.0/token
System.Net.Http.HttpClient.Default.ClientHandler: Information: Received HTTP response headers after 119.5397ms - 200
System.Net.Http.HttpClient.Default.LogicalHandler: Information: End processing HTTP request after 124.7733ms - 200
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] ScopeSet was missing from the token response, so using developer provided scopes in the result. 
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] Checking client info returned from the server..
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] Saving token response to cache..
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] [SaveTokenResponseAsync] ID Token not present in response. 
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] Cannot determine home account id - or id token or no client info and no subject 
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] [SaveTokenResponseAsync] Saving AT in cache and removing overlapping ATs...
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] Looking for scopes for the authority in the cache which intersect with https://graph.microsoft.com/.default
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] [Internal cache] Total number of cache partitions found while getting access tokens: 0
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] Intersecting scope entries count - 0
'<company>.IAM.AP-SelfService.Portal.Api.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.16\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] 
	=== Token Acquisition finished successfully:
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z]  AT expiration time: 6/9/2023 2:15:46 PM +00:00, scopes: https://graph.microsoft.com/.default. source: IdentityProvider
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] Fetched access token from host login.microsoftonline.com. 
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] 
[LogMetricsFromAuthResult] Cache Refresh Reason: NoCachedAccessToken
[LogMetricsFromAuthResult] DurationInCacheInMs: 0
[LogMetricsFromAuthResult] DurationTotalInMs: 590
[LogMetricsFromAuthResult] DurationInHttpInMs: 402

Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:47Z] TokenEndpoint: ****
'<company>.IAM.AP-SelfService.Portal.Api.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.16\System.IO.Compression.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'<company>.IAM.AP-SelfService.Portal.Api.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.16\System.Threading.Tasks.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'<company>.IAM.AP-SelfService.Portal.Api.exe' (CoreCLR: clrhost): Loaded 'C:\!Repos\cnpf-iam-GroupMgmt-SelfService\<company>.IAM.AP-SelfService.Portal.Api\bin\Debug\net6.0\Microsoft.IdentityModel.JsonWebTokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:50Z] MSAL MSAL.NetCore with assembly version '4.54.1.0'. CorrelationId(00000000-0000-0000-0000-000000000000)
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:50Z] === AcquireTokenSilent Parameters ===
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:50Z] LoginHint provided: False
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:50Z] Account provided: False
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:50Z] ForceRefresh: False
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:50Z] 
=== Request Data ===
Authority Provided? - True
Scopes - user.read
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 00000000-0000-0000-0000-000000000000
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:50Z] === Token Acquisition (SilentRequest) started:
	 Scopes: user.read
	Authority Host: login.microsoftonline.com
Microsoft.Identity.Web.TokenAcquisition: Warning: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:50Z] Only in-memory caching is used. The cache is not persisted and will be lost if the machine is restarted. It also does not scale for a web app or web API, where the number of users can grow large. In production, web apps and web APIs should use distributed caching like Redis. See https://aka.ms/msal-net-cca-token-cache-serialization
'<company>.IAM.AP-SelfService.Portal.Api.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.16\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'<company>.IAM.AP-SelfService.Portal.Api.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.16\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Identity.Web.TokenAcquisition: Error: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-06-09 13:15:50Z] Exception type: Microsoft.Identity.Client.MsalUiRequiredException
, ErrorCode: user_null
HTTP StatusCode 0
CorrelationId 

   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
Microsoft.Identity.Web.TokenAcquisition: Information: [MsIdWeb] An error occured during token acquisition: No account or login hint was passed to the AcquireTokenSilent call. 

MSAL.NetCore.4.54.1.0.MsalUiRequiredException: 
	ErrorCode: user_null
Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call. 
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForWebAppWithAccountFromCacheAsync(IConfidentialClientApplication application, ClaimsPrincipal claimsPrincipal, IEnumerable`1 scopes, String tenantId, MergedOptions mergedOptions, String userFlow, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
	StatusCode: 0 
	ResponseBody:  
	Headers: 
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

Status Code: 0
Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.

 ---> Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException: IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent. 
 ---> MSAL.NetCore.4.54.1.0.MsalUiRequiredException: 
	ErrorCode: user_null
Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call. 
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForWebAppWithAccountFromCacheAsync(IConfidentialClientApplication application, ClaimsPrincipal claimsPrincipal, IEnumerable`1 scopes, String tenantId, MergedOptions mergedOptions, String userFlow, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
	StatusCode: 0 
	ResponseBody:  
	Headers: 
   --- End of inner exception stack trace ---
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.DefaultAuthorizationHeaderProvider.CreateAuthorizationHeaderForUserAsync(IEnumerable`1 scopes, AuthorizationHeaderProviderOptions downstreamApiOptions, ClaimsPrincipal claimsPrincipal, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.TokenAcquisitionAuthenticationProvider.AuthenticateRequestAsync(HttpRequestMessage request)
   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.EntitlementManagementAssignmentPoliciesCollectionRequest.GetAsync(CancellationToken cancellationToken)
   at <company>.IAM.AP_SelfService.Portal.Api.Services.GraphApiManager.GetAccessPackageAssignmentPoliciesAsync(CancellationToken cancellationToken) in C:\!Repos\cnpf-iam-GroupMgmt-SelfService\<company>.IAM.AP-SelfService.Portal.Api\Services\GraphApiManager.cs:line 642
   at <company>.IAM.AP_SelfService.Portal.Api.Controllers.GraphApiController.getap(CancellationToken cancellationToken) in C:\!Repos\cnpf-iam-GroupMgmt-SelfService\<company>.IAM.AP-SelfService.Portal.Api\Controllers\GraphApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)


```

### Relevant code snippets

```csharp
see description of issue.
```

### Expected behavior

The call to Graph with ".WithAppOnly()" should just work even if paging is used/needed.

**Comment by Jan1503** [comment]
Well, workaround is quite easy :)

`var entitlementPoliciesRequest = entitlementPolicies?.NextPageRequest?.WithAppOnly() ?? _graphServiceClient`
