### ISSUE TITLE
Calling Downstream Web API fails when using ADFS.

### ISSUE THREAD

**Issue by robv8r** [AzureAD/microsoft-identity-web#2509]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.15.1

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

When using `EnableTokenAcquisitionToCallDownstreamApi` with ADFS, an error occurs.  (See Error Message section below).

An example application that reproduces this error can be found [here](https://github.com/robv8r/example-react-app).

The error is throw from [this section of code](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/b259cf00936a11a9cff789bf094935d8d31aea7f/src/client/Microsoft.Identity.Client/AppConfig/BaseAbstractApplicationBuilder.cs#L223) in the `BaseAbstractApplicationBuilder` class.

The error occurs when attempting to call the downstream Web API.  

### Reproduction steps

1. Clone https://github.com/robv8r/example-react-app
2. Setup ADFS with appropriate settings
3. Replace appsettings values with those from ADFS.

### Error message

```
MSAL.NetCore.4.56.0.0.MsalClientException: 
	ErrorCode: tenant_override_non_aad
Microsoft.Identity.Client.MsalClientException: Cannot use WithTenantId() in the application builder, because the authority Adfs doesn't support it
   at Microsoft.Identity.Client.BaseAbstractApplicationBuilder`1.ResolveAuthority()
   at Microsoft.Identity.Client.AbstractApplicationBuilder`1.BuildConfiguration()
   at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.BuildConcrete()
   at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Build()
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.DefaultAuthorizationHeaderProvider.CreateAuthorizationHeaderForUserAsync(IEnumerable`1 scopes, AuthorizationHeaderProviderOptions downstreamApiOptions, ClaimsPrincipal claimsPrincipal, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.CallApiInternalAsync(String serviceName, DownstreamApiOptions effectiveOptions, Boolean appToken, HttpContent content, ClaimsPrincipal user, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.CallApiForUserAsync[TOutput](String serviceName, Action`1 downstreamApiOptionsOverride, ClaimsPrincipal user, CancellationToken cancellationToken)
   at ExampleReactApp.Server.Controllers.DownstreamVersionController.Get(IDownstreamApi api, CancellationToken token) in C:\pj\git\example-react-app\src\server\Controllers\DownstreamVersionController.cs:line 14
   at lambda_method6(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json, text/plain, */*
Connection: close
Host: localhost:5173
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Bearer eyJ0...
Referer: https://localhost:5173/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
sec-ch-ua-platform: "Windows"
sec-ch-ua-mobile: ?0
DNT: 1
sec-ch-ua: "Microsoft Edge";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
```

### Relevant code snippets

```csharp
[ApiController]
[Route("[controller]")]
public class DownstreamVersionController : ControllerBase
{
    [HttpGet]
    public async Task<DownstreamVersionInfo?> Get([FromServices] IDownstreamApi api, CancellationToken token)
    {
        return await api.CallApiForUserAsync<DownstreamVersionInfo>(
            "api",
            options =>
            {
                options.HttpMethod = HttpMethod.Get.Method;
                options.RelativePath = $"api/Version/Get";
            },
            cancellationToken: token)
            .ConfigureAwait(false);
    }
}
```

### Expected behavior

Because ADFS has a fixed tenant (adfs), the Microsoft.Identity library should not throw an exception due to `WithTenantId()` being unsupported.

**Comment by robv8r** [comment]
Please note that the application targets net8.0.  The issue described above is also present in net7.0 using VS 2022 v17.7.4.

**Comment by jmprieur** [comment]
@robv8r : did you try to specify the "Authority" directly in the configuration file?

**Comment by robv8r** [comment]
@jmprieur - I've tried many different configuration options.  This morning, I attempted to specify the Authority in the appsettings.Development.json.  

Old

```
"AzureAd": {
  "Instance": "https://login.companyname.com/",
  "ClientId": "Enter_the_Confidential_Client_Id_Here",
  "ClientSecret": "Enter_the_Confidential_Client_Secret_here",
  "TenantId": "adfs"
}
```

New

```
"AzureAd": {
  "Authority": "https://login.companyname.com/adfs",
  "ClientId": "Enter_the_Confidential_Client_Id_Here",
  "ClientSecret": "Enter_the_Confidential_Client_Secret_here"
}
```

This results in an invalid "v2.0" URL segment when attempting to retrieve metadata.

```
Message: IDX20803: Unable to obtain configuration from: 'https://login.companyname.com/adfs/v2.0/.well-known/openid-configuration'.
```

The original error is still present.

```
Microsoft.Identity.Web.TokenAcquisition[300]
      [MsIdWeb] An error occured during token acquisition: IDW10501: Exception acquiring token for a confidential client.
      MSAL.NetCore.4.56.0.0.MsalClientException:
        ErrorCode: tenant_override_non_aad
Microsoft.Identity.Client.MsalClientException: Cannot use WithTenantId() in the application builder, because the authority Adfs doesn't support it
         at Microsoft.Identity.Client.BaseAbstractApplicationBuilder`1.ResolveAuthority()
         at Microsoft.Identity.Client.AbstractApplicationBuilder`1.BuildConfiguration()
         at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.BuildConcrete()
         at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Build()
         at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      MSAL.NetCore.4.56.0.0.MsalClientException:
        ErrorCode: tenant_override_non_aad
Microsoft.Identity.Client.MsalClientException: Cannot use WithTenantId() in the application builder, because the authority Adfs doesn't support it
         at Microsoft.Identity.Client.BaseAbstractApplicationBuilder`1.ResolveAuthority()
         at Microsoft.Identity.Client.AbstractApplicationBuilder`1.BuildConfiguration()
         at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.BuildConcrete()
         at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Build()
         at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
         at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
         at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
         at Microsoft.Identity.Web.DefaultAuthorizationHeaderProvider.CreateAuthorizationHeaderForUserAsync(IEnumerable`1 scopes, AuthorizationHeaderProviderOptions downstreamApiOptions, ClaimsPrincipal claimsPrincipal, CancellationToken cancellationToken)
         at Microsoft.Identity.Web.DownstreamApi.CallApiInternalAsync(String serviceName, DownstreamApiOptions effectiveOptions, Boolean appToken, HttpContent content, ClaimsPrincipal user, CancellationToken cancellationToken)
         at Microsoft.Identity.Web.DownstreamApi.CallApiForUserAsync[TOutput](String serviceName, Action`1 downstreamApiOptionsOverride, ClaimsPrincipal user, CancellationToken cancellationToken)
         at ExampleReactApp.Server.Controllers.DownstreamVersionController.Get(IDownstreamApi api, CancellationToken token) in C:\pj\git\example-react-app\src\server\Controllers\DownstreamVersionController.cs:line 14
         at lambda_method6(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Please let me know if I've misunderstood your recommendation, or if there are other steps I should try.

Thank you,
Rob

**Comment by robv8r** [comment]
My previous comment may have been missed.

Does this repository officially support ADFS?  If so, what's the best way to address this issue?

Thank you.

**Comment by robv8r** [comment]
Per the [documentation, ADFS is supported](https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/desktop-mobile/adfs-support).  Can you point me to documentation listing **officially** supported products?

**Comment by JimmyLS** [comment]
@robv8r I came acorss exact same issue as you and found a workaround. Specify the **Instance** to "https://{your adfs service name}/adfs" in ConfidentialClientApplicationOptions. During debug, I can see the "TenantId" will be set to null which will not trigger the error anymore. 

`            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                {
                    Configuration.Bind("Adfs", options);
                    options.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer = false }; // This is to disable the tenant ID verification in ADFS login scenario
                    options.SaveTokens = true; // This is to support sending "id_token_hint" in log out redirect to ADFS
                })
                .EnableTokenAcquisitionToCallDownstreamApi(
                    //Configuration.GetSection("TodoList:Scopes").Get<string[]>()
                    options =>
                    {
                        Configuration.GetSection("TodoList:Scopes").Get<string[]>();
                        options.Instance = "https://fs.contoso.com/adfs";
                    }
                )
                .AddInMemoryTokenCaches();`

**Comment by bgavrilMS** [comment]
@jmprieur - I think we should fix this in MSAL ? We can just have `WithTenantId` be no-op for ADFS. This avoids higher level APIs having to do "if ADFS ... do stuff".

**Comment by jmprieur** [comment]
Sure @bgavrilMS
Let's do that/

**Comment by jennyf19** [comment]
@bgavrilMS do you have an ETA on when this will be fixed in MSAL?

**Comment by bgavrilMS** [comment]
Will be fixed by adopting MSAL 4.61.1+ (not yet released)

**Comment by robv8r** [comment]
May I have an update on this issue please?
