### ISSUE TITLE
NullReferenceException when using AccessToken

### ISSUE THREAD

**Issue by Sebosek** [AzureAD/microsoft-identity-web#2520]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.15.1

### Web app

Not Applicable

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

I have a backend service with a registered OAuth client in Azure Portal (named "Anna Backend") and a frontend application in React that uses its own registered client (named "Anna Frontend"). The backend client exposes scope (Anna.Manage) and the frontend client has defined API permissions to use that scope.

I've created an API service, following all the steps in the tutorial: https://learn.microsoft.com/en-us/azure/active-directory/develop/web-api-tutorial-01-register-app. My configuration is the following.

```
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "ClientId": "api://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "TenantId": "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy",
    "Audience": "zzzzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz",
    "Scopes": "api://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/Anna.Manage"
  },
```

Program.cs config:
```
builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(configuration);

builder.Services.AddAuthorization(config =>
{
    config.AddPolicy("AnnaAuthorization", policy =>
        policy.Requirements.Add(new ScopeAuthorizationRequirement
        {
            RequiredScopesConfigurationKey = "AzureAd:Scopes"
        }));
});
```

Finally, minimal API config:
```
plan.MapGet("/",  async (CancellationToken token) => TypedResults.Ok(new object())
            .WithOpenApi(op => new(op)
            {
                OperationId = Name("read"),
                Tags = new List<OpenApiTag> { TAG }
            })
            .RequireAuthorization("AnnaAuthorization");
```

Now, for the React app, I've followed the tutorial https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-single-page-app-react-register-app.

With auth-config:
```
export const config = {
  auth: {
    clientId: "qqqqqqqqqq-qqqq-qqqq-qqqq-qqqqqqqqqqqq",
    authority: "https://login.microsoftonline.com/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy",
    redirectUri: "http://localhost:3000",
  },
  // ...
};

export const login = {
  scopes: ["User.Read", "api://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/Anna.Manage"]
};
```

To get the resources from the server, I have a small hook.
```
export const useRequest = (): UseRequest => {
  const { instance, accounts } = useMsal();

  const send = async <T>(path: string, opt: RequestInit | undefined = undefined) => {
    const auth = await instance.acquireTokenSilent({
      ...login,
      account: accounts[0],
      forceRefresh: true,
    });
    
    const predefined: RequestInit = {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${auth.accessToken}`, // <-- Using ACCESS TOKEN as is in the tutorial mentioned above
        // mode: 'cors',
      },
      credentials: 'include',
    };
    const request = await fetch(`https://localhost:7035${path}`, { ...predefined, ...opt });
    const body = await request.json();

    return (body as unknown) as T;
  };

  return { send };
};
```

However, the backend responses to authorized request with 401 with the following error in log:
```
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      Failed to validate the token.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.<>c__DisplayClass73_0.<ValidateSignature>b__0(SecurityKey x)
         at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignatureAndIssuerSecurityKey(String token, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateJWS(String token, TokenValidationParameters validationParameters, BaseConfiguration currentConfiguration, SecurityToken& signatureValidatedToken, ExceptionDispatchInfo& exceptionThrown)
      --- End of stack trace from previous location ---
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, JwtSecurityToken outerToken, TokenValidationParameters validationParameters, SecurityToken& signatureValidatedToken)
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[7]
      Bearer was not authenticated. Failure message: Object reference not set to an instance of an object.
```

Using IdToken instead of AccessToken ends with the error:
```
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[7]
      Bearer was not authenticated. Failure message: IDW10201: Neither scope or roles claim was found in the bearer token. Authentication scheme used: 'Bearer'.        
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      ScopeAuthorizationRequirement:Scope=
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
      AuthenticationScheme: Bearer was challenged.
```

### Reproduction steps

1. Create API service as is described in the first tutorial
2. Create React app as is describe in the second tutorial
3. Call protected API endpoint

### Id Web logs

info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:7035/api/plan application/json -
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      1 candidate(s) found for the request path '/api/plan'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint 'HTTP: GET /api/plan/'
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[15]
      Static files was skipped as the request already matched an endpoint.
dbug: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[2]
      The request has an origin header: 'http://localhost:3000'.
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10242: Security token: 'eyJ0eX...' has a valid signature.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10250: The associated certificate is valid. ValidFrom (UTC): '02.10.2022 18:06:49', Current time (UTC): '15.10.2023 12:04:07'.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10251: The associated certificate is valid. ValidTo (UTC): '02.10.2027 18:06:49', Current time (UTC): '15.10.2023 12:04:07'.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10239: Lifetime of the token is valid.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10234: Audience Validated.Audience: 'bc861529-0ec1-4c20-bfb1-211e0fbf32cb'
dbug: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10246: ValidateTokenReplay property on ValidationParameters is set to false. Exiting without validating the token replay.
dbug: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10255: TypeValidator property on ValidationParameters is null and ValidTypes is either null or empty. Exiting without validating the token type.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10245: Creating claims identity from the validated token: 'eyJ0e...'.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10241: Security token validated. token: 'eyJ0e...'.
dbug: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[7]
      Bearer was not authenticated. Failure message: IDW10201: Neither scope or roles claim was found in the bearer token. Authentication scheme used: 'Bearer'.        
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      ScopeAuthorizationRequirement:Scope=
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
      AuthenticationScheme: Bearer was challenged.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:7035/api/plan application/json - - 401 0 - 7.8421ms

### Relevant code snippets

```csharp
export const useRequest = (): UseRequest => {
  const { instance, accounts } = useMsal();

  const send = async <T>(path: string, opt: RequestInit | undefined = undefined) => {
    const auth = await instance.acquireTokenSilent({
      ...login,
      account: accounts[0],
      forceRefresh: true,
    });
    
    const predefined: RequestInit = {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${auth.accessToken}`, // <-- Using ACCESS TOKEN as is in the tutorial mentioned above
        // mode: 'cors',
      },
      credentials: 'include',
    };
    const request = await fetch(`https://localhost:7035${path}`, { ...predefined, ...opt });
    const body = await request.json();

    return (body as unknown) as T;
  };

  return { send };
};
```
```


### Regression

_No response_

### Expected behavior

The API endpoint response with 200 or 403.

**Comment by JonasDev17** [comment]
I have the same issue.

  ```csharp
  services
        .AddAuthentication()
            .AddJwtBearer(options =>
            {
                var jwtSettings = config.GetSection("SecuritySettings:JwtSettings").Get<JwtSettings>();
                byte[] key = Encoding.ASCII.GetBytes(jwtSettings.Key);

                options.RequireHttpsMetadata = false;
                options.SaveToken = true;
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(key),
                    ValidateIssuer = false,
                    ValidateLifetime = true,
                    ValidateAudience = false,
                    RoleClaimType = ClaimTypes.Role,
                    ClockSkew = TimeSpan.Zero
                };

                options.Events = new JwtBearerEvents
                {
                    OnChallenge = context =>
                    {
                        context.HandleResponse();
                        if (!context.Response.HasStarted)
                        {
                            throw new UnauthorizedException("Authentication Failed.");
                        }

                        return Task.CompletedTask;
                    },
                    OnForbidden = _ => throw new ForbiddenException("You are not authorized to access this resource."),
                    OnMessageReceived = context =>
                    {
                        var accessToken = context.Request.Query["access_token"];

                        if (!string.IsNullOrEmpty(accessToken) &&
                            context.HttpContext.Request.Path.StartsWithSegments("/notifications"))
                        {
                            // Read the token out of the query string
                            context.Token = accessToken;
                        }

                        return Task.CompletedTask;
                    }
                };
            })
            .AddMicrosoftIdentityWebApi(config, "SecuritySettings:AzureAd", "AzureAD");

        services.AddAuthorization(options =>
        {
            var defaultAuthorizationPolicyBuilder = new AuthorizationPolicyBuilder(
                JwtBearerDefaults.AuthenticationScheme,
                "AzureAD");
            defaultAuthorizationPolicyBuilder =
                defaultAuthorizationPolicyBuilder.RequireAuthenticatedUser();
            options.DefaultPolicy = defaultAuthorizationPolicyBuilder.Build();
        });

**Comment by JonasDev17** [comment]
made slight change:

```csharp

.AddAuthentication(options =>
             {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
             })
```
and now jwt auth works on protected endpoints but azure ad fails with ` Object reference not set to an instance of an object.`

**Comment by JonasDev17** [comment]
I turned on verbose logging:

```
[14:36:59 DBG] Entity Framework Core 7.0.12 initialized 'ApplicationDbContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL:7.0.11+c25a0d7b68d66c6ab3849a3b4333964faea6adc9' with options: SensitiveDataLoggingEnabled MigrationsAssembly=Migrators.PostgreSQL
[14:37:26 DBG] Compiling query expression:
'DbSet<ApplicationUser>()
    .Where(u => u.ObjectId == __objectId_0)
    .FirstOrDefault()'
[14:37:26 DBG] Generated query execution expression:
'queryContext =>
{
    queryContext.AddParameter(
        name: "__ef_filter__Id_0",
        value: (object)Invoke(queryContext => ((ApplicationDbContext)queryContext.Context).TenantInfo.Id, queryContext));
    return ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<ApplicationUser>(
        asyncEnumerable: new SingleQueryingEnumerable<ApplicationUser>(
            (RelationalQueryContext)queryContext,
            RelationalCommandCache.QueryExpression(
                Projection Mapping:
                    EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: ApplicationUser.Id (string) Required PK AfterSave:Throw, 0], [Property: ApplicationUser.AccessFailedCount (int) Required, 1], [Property: ApplicationUser.AuthenticationType (AuthenticationType?), 2], [Property: ApplicationUser.ConcurrencyStamp (string) Concurrency, 3], [Property: ApplicationUser.Email (string) MaxLength(256), 4], [Property: ApplicationUser.EmailConfirmed (bool) Required, 5], [Property: ApplicationUser.FirstName (string), 6], [Property: ApplicationUser.ImageUrl (string), 7], [Property: ApplicationUser.IsActive (bool) Required, 8], [Property: ApplicationUser.LastName (string), 9], [Property: ApplicationUser.LockoutEnabled (bool) Required, 10], [Property: ApplicationUser.LockoutEnd (DateTimeOffset?), 11], [Property: ApplicationUser.NormalizedEmail (string) Index MaxLength(256), 12], [Property: ApplicationUser.NormalizedUserName (string) Index MaxLength(256), 13], [Property: ApplicationUser.ObjectId (string) MaxLength(256), 14], [Property: ApplicationUser.PasswordHash (string), 15], [Property: ApplicationUser.PhoneNumber (string), 16], [Property: ApplicationUser.PhoneNumberConfirmed (bool) Required, 17], [Property: ApplicationUser.RefreshToken (string), 18], [Property: ApplicationUser.RefreshTokenExpiryTime (DateTime) Required, 19], [Property: ApplicationUser.SecurityStamp (string), 20], [Property: ApplicationUser.TenantId (string) Required Index MaxLength(64), 21], [Property: ApplicationUser.TwoFactorEnabled (bool) Required, 22], [Property: ApplicationUser.UserName (string) MaxLength(256), 23] }
                SELECT TOP(1) u.Id, u.AccessFailedCount, u.AuthenticationType, u.ConcurrencyStamp, u.Email, u.EmailConfirmed, u.FirstName, u.ImageUrl, u.IsActive, u.LastName, u.LockoutEnabled, u.LockoutEnd, u.NormalizedEmail, u.NormalizedUserName, u.ObjectId, u.PasswordHash, u.PhoneNumber, u.PhoneNumberConfirmed, u.RefreshToken, u.RefreshTokenExpiryTime, u.SecurityStamp, u.TenantId, u.TwoFactorEnabled, u.UserName
                FROM Identity.Users AS u
                WHERE (u.TenantId == @__ef_filter__Id_0) && (u.ObjectId == @__objectId_0)),
            null,
            Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, ApplicationUser>,
            HIS.Simple.Sync.Infrastructure.Persistence.Context.ApplicationDbContext,
            False,
            False,
            True
        ),
        cancellationToken: queryContext.CancellationToken);
}'
[14:37:34 ERR] Exception occurred while processing message.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method340(Closure, QueryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at HIS.Simple.Sync.Infrastructure.Identity.UserService.GetOrCreateFromPrincipalAsync(ClaimsPrincipal principal) in C:\xxxxxxxxxx\src\Infrastructure\Identity\UserService.CreateUpdate.cs:line 31
   at HIS.Simple.Sync.Infrastructure.Auth.AzureAd.AzureAdJwtBearerEvents.TokenValidated(TokenValidatedContext context) in C:\xxxxxxxxxx\src\Infrastructure\Auth\AzureAd\AzureAdJwtBearerEvents.cs:line 92
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
[14:37:34 ERR] Authentication failed Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method340(Closure, QueryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at HIS.Simple.Sync.Infrastructure.Identity.UserService.GetOrCreateFromPrincipalAsync(ClaimsPrincipal principal) in Cxxxxxxxxxxsrc\Infrastructure\Identity\UserService.CreateUpdate.cs:line 31
   at HIS.Simple.Sync.Infrastructure.Auth.AzureAd.AzureAdJwtBearerEvents.TokenValidated(TokenValidatedContext context) in C:\xxxxxxxxxx\src\Infrastructure\Auth\AzureAd\AzureAdJwtBearerEvents.cs:line 92
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   
```

The error happens in the `Microsoft.EntityFrameworkCore.Query.Internal QueryCompiler.cs` in the function `ExecuteAsync` :

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25738474/ff323c72-5922-4ee7-b6c8-6cf6ecb770f0)

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25738474/9cb61943-e15d-40a1-8e21-263032d54726)

**Comment by JonasDev17** [comment]
@Sebosek do you use the FSH Template, Finbuckle Multitenant or a different global query filter?

**Comment by JonasDev17** [comment]
turns out that in my case it was an [issue with Finbuckle.Multitenant](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/765) which does not support using .WithClaimStrategy with multiple authentication schemes.

**Comment by jennyf19** [comment]
closing, as external, but please reopen @Sebosek if you still hit the issue and we will investigate. thanks.
