### ISSUE TITLE
Dll binding issue using latest packages

### ISSUE THREAD

**Issue by craigb** [AzureAD/microsoft-identity-web#2557]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.TokenAcquisition

### Microsoft.Identity.Web version

2.13.4

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

> Could not load file or assembly 'Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=6.33.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

Updated to latest packages for a CVE fix -- this pushes Microsoft.IdentityModel.* to 6.34.0.0. But, when attempting to get a token from an ITokenAcquirer, something appears to want the 6.33 version.

### Reproduction steps

 1. Set up an app registration
 2. Set up a trusted SN+I
 3. Generate a cert
 4. Set up an ASPNETCore service
 5. Set up a TokenAcquirerFactory:
    1. Configure a MicrosoftIdentityApplicationOptions to point to the app + cert.
    2. Build it and put it in the DI contianer.
 8. Resolve it in a controller
 9. Create an ITokenAcquirer from it
 10. Try to acquire an app token from the resolved ITokenAcquirer.

### Error message

Could not load file or assembly 'Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=6.33.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified. 
  at Microsoft.Identity.Web.MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(MicrosoftIdentityOptions microsoftIdentityOptions, MergedOptions mergedOptions)
   at Microsoft.Identity.Web.MicrosoftIdentityOptionsMerger.PostConfigure(String name, MicrosoftIdentityOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.Identity.Web.Hosts.DefaultTokenAcquisitionHost.GetOptions(String authenticationScheme, String& effectiveAuthenticationScheme)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquirer.Microsoft.Identity.Abstractions.ITokenAcquirer.GetTokenForAppAsync(String scope, AcquireTokenOptions tokenAcquisitionOptions, CancellationToken cancellationToken)
   at MyProject.JunkFunk(TimerInfo timer) in D:\src\MyProject\JunkFunc.cs:line 32

### Relevant code snippets

```csharp
[FunctionName("TEST")]
    public async Task DoTimer([TimerTrigger("0 0 */2 * * *", RunOnStartup =true, UseMonitor = true)] TimerInfo timer)
    {
        try
        {
            var tokenAcquirer = _factory.GetTokenAcquirer("72f988bf-86f1-41af-91ab-2d7cd011db47");
            var token = await tokenAcquirer.GetTokenForAppAsync("https://vault.azure.net/.default");
            Console.WriteLine(token.AccessToken);
        }
        catch(Exception ex)
        {
            Debugger.Break();
            throw;
        }
    }
```

### Regression

2.15.3

### Expected behavior

Token acquired successfully.

FWIW: this looks like an issue with the minor version being part of the AssemblyVersion for the Microsoft.IdentityModel.Protocols.OpenIdConnect package (and its siblings). I think the quick fix is to update the 6.33 version in this codebase to 6.34, and only use the major version in the assembly version of the dependencies for the future.
https://github.com/AzureAD/microsoft-identity-web/blob/85cc6811bab9caa328f3970655456ac27463ad5f/Directory.Build.props#L75

**Comment by jennyf19** [comment]
@craigb will follow-up with you directly.
