### ISSUE TITLE
Issue while using msidentity-app-sync 

### ISSUE THREAD

**Issue by MauRiEEZZZ** [AzureAD/microsoft-identity-web#2559]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.15.3

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

Using the ms-identity-sync tool doesn't work following instructions that are provided.

I am using MacOS 13.3.1 (a) it is running on an M2 processor.

### Reproduction steps

I started here: https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-blazor-server

At the step Use the Microsoft Identity App Sync Tool

``` 
You must install or update .NET to run this application.

App: /Users/<redacted>/.dotnet/tools/msidentity-app-sync
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (x64)
.NET location: /usr/local/share/dotnet/x64

The following frameworks were found:
  6.0.14 at [/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=osx.13-x64
```

I wasn't sure this message is correct as NetCore 5.0 is not supported now and also I am using arm64 architecture.

I uninstalled the msidentity-app-sync

And I followed the instructions to build and install the tool described here: https://github.com/AzureAD/microsoft-identity-web/blob/master/tools/app-provisioning-tool/README.md#option-2-build-and-install-from-the-repository

I executed the msidentity-app-sync command again I described in the first article and the exception appeared that is provided in Error message.

### Error message

```
Detected project type dotnet-webapp.
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Identity.App.DeveloperCredentials.MsalTokenCredential.GetOrCreateApp() in /Users/<redacted>/Projects/identityweb/microsoft-identity-web/tools/app-provisioning-tool/app-provisioning-lib/DeveloperCredentials/MsalTokenCredential.cs:line 45
   at Microsoft.Identity.App.DeveloperCredentials.MsalTokenCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken) in /Users/<redacted>/Projects/identityweb/microsoft-identity-web/tools/app-provisioning-tool/app-provisioning-lib/DeveloperCredentials/MsalTokenCredential.cs:line 79
   at Microsoft.Identity.App.MicrosoftIdentityPlatformApplication.TokenCredentialAuthenticationProvider.AuthenticateRequestAsync(RequestInformation request, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken) in /Users/<redacted>/Projects/identityweb/microsoft-identity-web/tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/TokenCredentialAuthenticationProvider.cs:line 35
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims, Boolean isStreamResponse)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Beta.Organization.OrganizationRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at Microsoft.Identity.App.MicrosoftIdentityPlatformApplication.MicrosoftIdentityPlatformApplicationManager.GetTenant(GraphServiceClient graphServiceClient) in /Users/<redacted>/Projects/identityweb/microsoft-identity-web/tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/MicrosoftIdentityPlatformApplicationManager.cs:line 171
   at Microsoft.Identity.App.MicrosoftIdentityPlatformApplication.MicrosoftIdentityPlatformApplicationManager.CreateNewApp(TokenCredential tokenCredential, ApplicationParameters applicationParameters) in /Users/<redacted>/Projects/identityweb/microsoft-identity-web/tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/MicrosoftIdentityPlatformApplicationManager.cs:line 36
   at Microsoft.Identity.App.AppProvisioningTool.ReadOrProvisionMicrosoftIdentityApplication(TokenCredential tokenCredential, ApplicationParameters applicationParameters) in /Users/<redacted>/Projects/identityweb/microsoft-identity-web/tools/app-provisioning-tool/app-provisioning-lib/Tool/AppProvisioningTool.cs:line 278
   at Microsoft.Identity.App.AppProvisioningTool.Run() in /Users/<redacted>/Projects/identityweb/microsoft-identity-web/tools/app-provisioning-tool/app-provisioning-lib/Tool/AppProvisioningTool.cs:line 110
   at Microsoft.Identity.App.Program.Main(String tenantId, String username, String clientId, String folder, String clientSecret, String susiPolicyId, String apiClientId, String appIdUri, Nullable`1 unregister) in /Users/<redacted>/Projects/identityweb/microsoft-identity-web/tools/app-provisioning-tool/app-provisioning-tool/Program.cs:line 79
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Relevant code snippets

```csharp
dotnet new blazorserver --auth SingleOrg --calls-graph

msidentity-app-sync [--tenant-id <tenantId>] --client-id <clientId>
```

### Expected behavior

The ms-identity-sync should have tool created the application in Entra id.

**Comment by jmprieur** [comment]
Several things here:
- we need to ensure we use / as a path separator and not \. Or better the Path.Separator property
- we need to re-release the tool (Which was updated, but no re-released as VS does great)

**Comment by jasonalexander-ja** [comment]
I was able to install and run msidentity-app-sync on an M1 Mac without the `You must install or update .NET to run this application.` error, but was just getting the `Value cannot be null. (Parameter 'path1')` error, I started looking into where this was coming from and saw in [MsalTokenCredential.cs#L47](https://github.com/AzureAD/microsoft-identity-web/blob/master/tools/app-provisioning-tool/app-provisioning-lib/DeveloperCredentials/MsalTokenCredential.cs#L47) that the cache handling just hadn't been set up for Linux/MacOS. 

I had a quick go at making a patch locally copying the cache config from an example I found in [microsoft-authentication-cli](https://github.com/AzureAD/microsoft-authentication-cli/blob/main/src/MSALWrapper/PCACache.cs) that I have committed in a fork [here](https://github.com/jasonalexander-ja/microsoft-identity-web/blob/master/tools/app-provisioning-tool/app-provisioning-lib/DeveloperCredentials/MsalTokenCredential.cs#L56), that config will definitely need to be reviewed. 

```c#
string cachePath = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
    ? @"AppData\Local\.IdentityService"
    : @".IdentityService";
string cacheDir = Path.Combine(MsalCacheHelper.UserRootDirectory, cachePath);

// TODO: Review token cache config. 
string clientId = "04b07795-8ddb-461a-bbee-02f9e1bf7b46";
var storageProperties =
        new StorageCreationPropertiesBuilder(
            "msal.cache",
            cacheDir)
        .WithLinuxKeyring(
            LinuxKeyRingSchema,
            LinuxKeyRingCollection,
            LinuxKeyRingLabel,
            LinuxKeyRingAttr1,
            LinuxKeyRingAttr2)
        .WithMacKeyChain(
            MacOSServiceName,
            MacOSAccountName)
        .Build();
```

I have managed to get it to run without error, this does however lead to 2 further issues (having followed the above-mentioned tutorial [Create a Blazor Server app that uses the Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-blazor-server)), the first being that it updates the packages `Microsoft.Identity.Web` and `Microsoft.Identity.Web.UI` from `1.16.0` to `2.16.3` which is causing a build error:

```
[project-root]/Program.cs(17,1): error CS7069: Reference to type 'MicrosoftIdentityAppCallsWebApiAuthenticationBuilder' claims it is defined in 'Microsoft.Identity.Web', but it could not be found
```

The second is that although it seems to correctly create a user secret, it doesn't set it inside the user secrets at all, and sets the `AzureAd:ClientSecret` string in appsettings.json to `Application.ClientSecret`, whereas on Windows this is set to `See user secrets`.

I will continue to look into this as much as I can and see what is happening differently on Windows vs MacOS and update further.

**Comment by jasonalexander-ja** [comment]
Update: 

For the issue with the package versions in the target solution being updated, I tried running the master branch (without any of my changes) on Windows and it behaved in the same way strangely, so looks to be a separate issue? Thankfully this is just mitigated by reverting changes on the affected .csproj file. 

I was able to figure out what was causing the user secrets not being set, in the file [CodeWriter.cs#L139](https://github.com/AzureAD/microsoft-identity-web/blob/master/tools/app-provisioning-tool/app-provisioning-lib/CodeReaderWriter/CodeWriter.cs#L139) there is a case in the switch statement specifically for handling setting the client secret, and currently it was only set up for setting user secrets on Windows, but following the mentioned guide [How the Secret Manager tool works](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=windows#how-the-secret-manager-tool-works-1) it looks to be a fairly simple case of giving one path for Windows and another for Linux/MacOS, I made the change [here](https://github.com/jasonalexander-ja/microsoft-identity-web/blob/master/tools/app-provisioning-tool/app-provisioning-lib/CodeReaderWriter/CodeWriter.cs#L141). 

```c#
string userHome = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
string secretsPath = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
    ? @"AppData\Roaming\Microsoft\UserSecrets\"
    : @".microsoft/usersecrets/";
string path = Path.Combine(
    userHome,
    secretsPath,
    reconciledApplicationParameters.SecretsId,
    "secrets.json")!;
```

This change seems to now make the tool behave and work the same MacOS/Linux as on Windows. 

Would it help if I opened a PR for this @jmprieur ? I realise the edits I made particularly around the cache files may need reviewing but I'm more than happy to make any adjustments as necessary and help/collaborate where I can on this issue.

**Comment by jasonalexander-ja** [comment]
Made a mistake above, I thought `MsalCacheHelper.UserRootDirectory` would return the user's root directory, but after running a debug on Windows it actually gets the root cache directory for the user, which in hindsight makes total sense, I replaced: 

```c#
string cachePath = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
    ? @"AppData\Local\.IdentityService"
    : @".IdentityService";
string cacheDir = Path.Combine(MsalCacheHelper.UserRootDirectory, cachePath);
``` 

With just the line: 

```c#
string cacheDir = Path.Combine(MsalCacheHelper.UserRootDirectory, @".IdentityService");
```
