### ISSUE TITLE
JsonException when attempting to deserialize an empty body

### ISSUE THREAD

**Issue by wohlly** [AzureAD/microsoft-identity-web#2560]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.15.3

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Not Applicable

### Description

After switching from DownstreamWebApi to DownstreamApi, all web API calls which return an empty string are broken.

Previously, there was a condition in the CallWebApiForUserAsync method before calling Deserialize:
```
string content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

if (string.IsNullOrWhiteSpace(content))
{
    return default;
}

return JsonSerializer.Deserialize<TOutput>(content, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
```

In the updated version, the DeserializeOutput method does not check the string content first
```
string stringContent = await content.ReadAsStringAsync();
return JsonSerializer.Deserialize<TOutput>(stringContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
```

### Reproduction steps

1. Use CallApiForUserAsync with a URL that returns an empty body

### Error message

```
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinal
Block is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, 
when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 b
ytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)       
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)       
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)   
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Microsoft.Identity.Web.DownstreamApi.DeserializeOutput[TOutput](HttpResponseMessage response, DownstreamApiOptions effectiveOptions)   
   at Microsoft.Identity.Web.DownstreamApi.CallApiForUserAsync[TInput,TOutput](String serviceName, TInput input, Action`1 downstreamApiOption
sOverride, ClaimsPrincipal user, CancellationToken cancellationToken)
   ...
```

### Relevant code snippets

```csharp
_downstreamApi.CallApiForUserAsync<TInput, TOutput>(
    ServiceName,
    input);
```

### Regression

Before "Id.Abstractions 1.0.5-preview" commit

### Expected behavior

Method should return default/null.

**Comment by robertodelbuono** [comment]
Some news about it? I have the same issue when API returns NoContent().
I have tried to build my own Deserializer but I have not the TOutput in the signature of the method. So it is not possibile to know the Type.
