### ISSUE TITLE
[Bug] Error after upgrading Microsoft.Identity.Web from 1.25.3 to 2.15.5 for Azure B2C configuration

### ISSUE THREAD

**Issue by Sathish2407** [AzureAD/microsoft-identity-web#2603]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.15.5

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

Not Applicable

### Description

Azure B2C was working fine and able to authenticate my Web API .Net 6.0 in Microsoft.Identity.Web 1.25.3 version. I was trying to upgrade my Web API to .Net 8.0 and due to this I am upgrading to 2.15.5 version, I am getting 500 error. 

Please note I have my Azure B2C configurations in Key vault. Those Key vault values are read and assigned through MicrosoftIdentityOptions. I would not want my B2C values exposed in appsettings.json as I am having different stages of environments. 

I ended up with this error only after upgrading to 2.15.5 and after research, this error was happening from 2.5.0 version onwards.

### Reproduction steps

Upgrade from 1.25.3 to 2.15.5

### Error message

System.ArgumentNullException: IDW10106: The 'ClientId' option must be provided. 
   at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__2(JwtBearerOptions options, IServiceProvider serviceProvider, IMergedOptionsStore mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`4.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Relevant code snippets

```csharp
Code in appsettings.json file.

{
  "AzureKeyVault": {
    "Uri": "https://xxxxxxxxxxxxxxx.azure.net/",
    "ADB2CInstance": "ADB2CInstance",
    "ADB2CClientId": "ADB2CClientId",
    "ADB2CDomain": "ADB2CDomain",
    "ADB2CSignUpSignInPolicyId": "ADB2CSignUpSignInPolicyId"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  }
}

Code in Program.cs file.

var builder = WebApplication.CreateBuilder(args);

//Gets the key vault
string vaultName = builder.Configuration.GetSection("AzureKeyVault:Uri").Value;


builder.WebHost.ConfigureAppConfiguration((context, config) =>
{
    IConfigurationRoot builtConfig = config.Build();
    string vaultName = builtConfig.GetSection("AzureKeyVault:Uri").Value.ToString();
    config
            .AddJsonFile(Path.Combine(context.HostingEnvironment.ContentRootPath, "appsettings.json"), optional: true, reloadOnChange: true)
            .AddJsonFile(Path.Combine(context.HostingEnvironment.ContentRootPath, $"appsettings.{context.HostingEnvironment.EnvironmentName}.json"), optional: true, reloadOnChange: true)
            .AddAzureKeyVault(new Uri(vaultName), new DefaultAzureCredential());
});

var configuration = builder.Configuration;
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddMicrosoftIdentityWebApi(configuration);
builder.Services.Configure<MicrosoftIdentityOptions>(option =>
{
    option.Instance = builder.Configuration.GetValue<string>(builder.Configuration.GetValue<string>("AzureKeyVault:ADB2CInstance"));
    option.ClientId = builder.Configuration.GetValue<string>(builder.Configuration.GetValue<string>("AzureKeyVault:ADB2CClientId"));
    option.Domain = builder.Configuration.GetValue<string>(builder.Configuration.GetValue<string>("AzureKeyVault:ADB2CDomain"));
    option.SignUpSignInPolicyId = builder.Configuration.GetValue<string>(builder.Configuration.GetValue<string>("AzureKeyVault:ADB2CSignUpSignInPolicyId"));
});
```

### Expected behaviour

Should authenticate successfully using Azure B2C in Web API .Net 8.0 by reading values through KeyVault.

**Comment by michiproep** [comment]
builder.Services.Configure<MicrosoftIdentityOptions>(**JwtBearerDefaults.AuthenticationScheme,** option => ...

**Comment by Sathish2407** [comment]
@michiproep is that a solution you want me to try out?

**Comment by michiproep** [comment]
@Sathish2407 : yes, see https://github.com/AzureAD/microsoft-identity-web/wiki/v2.0#breaking-changes

**Comment by Sathish2407** [comment]
@michiproep Thank you, it is working as expected. I will keep an eye on the wiki hereafter.
