### ISSUE TITLE
Use of DefaultAzureCredential in ManagedIdentityClientAssertion's GetClientAssertion method can be problemmatic

### ISSUE THREAD

**Issue by psignoret** [AzureAD/microsoft-identity-web#2644]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.16.1

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

The [GetClientAssertion implementation](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs#L32) in [ManagedIdentityClientAssertion](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs) uses an instance of [DefaultAzureCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) to acquire a token for `api://AzureADTokenExchange`. (This token is then used as the client assertion in a Client Credentials token request.)

Using [DefaultAzureCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) here leads to unnecessary delays and confusing errors when run in an environment that does not have access to authenticate as a managed identity. For example, when debugging locally, it will fall back to attempting to obtain a token for the `api://AzureADTokenExchange` resource using Azure CLI (with an [AzureCliCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azureclicredential?view=azure-dotnet)), which is guaranteed to fail. (An example of the confusing error message is shown below.)

As a [ManagedIdentityClientAssertion](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.web.managedidentityclientassertion?view=msal-model-dotnet-latest) is by-design only intended to be used when the environment can authenticate as a managed identity, I propose it should directly use a [ManagedIdentityCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet) to obtain the tokendirectly, instead of a [DefaultAzureCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) to obtain the token.  When run in an environment that can't authenticate as a managed identity, this would result in a clear and simple error. It will also avoid other error cases such as incorrectly using a token for different app identity because certain environment variables were set (EnvironmentCredential and WorkloadIdentityCredential, both of which would take precedence over ManagedIdentityCredential), or wasting time attempting fallback options which are guaranteed to fail (e.g. AzureCliCredential and AzurePowerShellCredential).

### Reproduction steps

1. In an environment that does not have access to authenticate as a managed identity, run the following:

   ```cs
   await new ClientAssertionCredential(
        // tenantId and clientId parameters don't matter for this repro, the error is thrown before they're used
		"00000000-0000-0000-0000-000000000000", "00000000-0000-0000-0000-000000000000",
		new ManagedIdentityClientAssertion(null).GetSignedAssertion)
	.GetTokenAsync(new TokenRequestContext(new[] { "https://graph.microsoft.com/.default" }));
   ```

### Error message

Message:

```none
DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
- WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/workloadidentitycredential/troubleshoot
- ManagedIdentityCredential authentication unavailable. Multiple attempts failed to obtain a token from the managed identity endpoint.
- Process "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS001: This account 'phsignor@microsoft.com' needs re-authentication. Please go to Tools->Options->Azure Services Authentication, and re-authenticate the account you want to use..
- Azure CLI authentication failed due to an unknown error. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/azclicredential/troubleshoot ERROR: AADSTS700019: Application ID fb60f99c-7a34-4190-8149-302f77469936 cannot be used or is not authorized. Trace ID: 719d622b-b4ce-429c-a291-c7994b9d7800 Correlation ID: 57a707c1-7710-4840-a759-3cf11bde2e95 Timestamp: 2024-01-17 21:28:25Z
Interactive authentication is needed. Please run:
az login --scope api://AzureADTokenExchange/.default
- Azure PowerShell authentication failed due to an unknown error. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/powershellcredential/troubleshoot #< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">_x001B_[31;1mGet-AzAccessToken: _x001B_[0m_x000D__x000A_</S><S S="Error">_x001B_[31;1m_x001B_[36;1mLine |_x001B_[0m_x000D__x000A_</S><S S="Error">_x001B_[31;1m_x001B_[36;1m_x001B_[36;1m  12 | _x001B_[0m $token = _x001B_[36;1mGet-AzAccessToken -ResourceUrl 'api://AzureADTokenExchange'_x001B_[0m_x000D__x000A_</S><S S="Error">_x001B_[31;1m_x001B_[36;1m_x001B_[36;1m_x001B_[0m_x001B_[36;1m_x001B_[0m_x001B_[36;1m     | _x001B_[31;1m          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x001B_[0m_x000D__x000A_</S><S S="Error">_x001B_[31;1m_x001B_[36;1m_x001B_[36;1m_x001B_[0m_x001B_[36;1m_x001B_[0m_x001B_[36;1m_x001B_[31;1m_x001B_[31;1m_x001B_[36;1m     | _x001B_[31;1mSharedTokenCacheCredential authentication failed: AADSTS700019: Application ID fb60f99c-7a34-4190-8149-302f77469936 cannot be used or is not authorized. Trace ID: fdbb961a-8b01-4da1-8191-b0738089bb00 Correlation ID: 3de4fca4-3964-4663-8470-26332db91273 Timestamp: 2024-01-17 21:28:29Z_x001B_[0m_x000D__x000A_</S></Objs>
- Azure Developer CLI could not be found.
```

Stack trace:

```none
at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
at Microsoft.Identity.Web.ManagedIdentityClientAssertion.GetClientAssertion(CancellationToken cancellationToken)
at Microsoft.Identity.Web.ClientAssertionProviderBase.GetSignedAssertion(CancellationToken cancellationToken)
at Microsoft.Identity.Client.Internal.ClientCredential.SignedAssertionDelegateClientCredential.AddConfidentialClientParametersAsync(OAuth2Client oAuth2Client, ILoggerAdapter logger, ICryptographyManager cryptographyManager, String clientId, String tokenEndpoint, Boolean sendX5C, CancellationToken cancellationToken)
at Microsoft.Identity.Client.OAuth2.TokenClient.AddBodyParamsAndHeadersAsync(IDictionary`2 additionalBodyParameters, String scopes, CancellationToken cancellationToken)
at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientCoreAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
at Azure.Identity.ClientAssertionCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
at Azure.Identity.ClientAssertionCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
at UserQuery.Main(), line 4
```

### Relevant code snippets

```csharp
await new ClientAssertionCredential(
	// tenantId and clientId parameters don't matter for this repro, the error is thrown before they're used
	"00000000-0000-0000-0000-000000000000", "00000000-0000-0000-0000-000000000000",
	new ManagedIdentityClientAssertion(null).GetSignedAssertion)
.GetTokenAsync(new TokenRequestContext(new[] { "https://graph.microsoft.com/.default" }));
```

### Expected behavior

An error message specifically about not being able to use a managed identity. For example, the same repro but using a callback implementation that uses a `ManagedIdentityCredential` instead of `DefaultAzureCredential` would give:

```none
ManagedIdentityCredential authentication unavailable. Multiple attempts failed to obtain a token from the managed identity endpoint.
```

**Comment by jmprieur** [comment]
Thanks @psignoret. This has been on the backlog for a while (https://github.com/AzureAD/microsoft-identity-web/issues/2551)
@bgavrilMS : do you remember who we agreed would replace the DefaultAzureCredential by MSAL.NET (bullet point 2)
