### ISSUE TITLE
downstreamApi does not correctly handle text response

### ISSUE THREAD

**Issue by karlschriek** [AzureAD/microsoft-identity-web#2719]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.DownstreamApi

### Microsoft.Identity.Web version

2.17,1

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Not Applicable

### Description

downstreamApi will attempt to deserialize JSON, even if expected return type is a string.

I have attempted a fix by overriding the default deserializer with something along the following lines

```c#
  options.Deserializer = async Task<string> (content) =>
  {
      var result = await content.ReadAsStringAsync();
      return result;
  };
```          
 However, I can't find a way to this can be properly awaited, since options.Deserializer expects a non-async function.

### Reproduction steps

Create a downstream API service that return raw text (i.e., not JSON encoded text). Then call that API using:

```c#
var result = await _downstreamApi.PostForAppAsync<object, string>( "MyApi", null);
```

### Error message

```
'r' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
    System.Text.Json.JsonException: 'r' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'r' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

```

### Relevant code snippets

```csharp
result = await _downstreamApi.PostForAppAsync<object, string>("MyApi", null);
```

### Expected behavior

I would expect the downstreamApi to not attempt to parse content if the expected return value is of type `string`

**Comment by bgavrilMS** [comment]
Hi @karlschriek - there are methods that return an `HttpResponseMessage` instead, that do not parse the message content. Can't those be used instead? 

https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs#L77
