### ISSUE TITLE
IDW10502 | MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call

### ISSUE THREAD

**Issue by BernieEllis** [AzureAD/microsoft-identity-web#3006]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

3.1

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Distributed caches

### Description

Hi, I know this is a pretty popular issue (MsalUiRequiredExeption) and I've seen many issues reported with varying results. Unfortunately, none of solutions/workarounds/documentation/guidance seems to be helping me. Here's my setup:

1. .NET 8.0 Blazor web app (Unified model) w/ InteractiveServer render mode turned on globally, signs in users. I'm using OpenID Connect authentication scheme here. The app registration for this app is requesting id and access tokens.
2. This web app calls a .NET 8.0 web api setup with MVC controllers to call downstream APIs such as Azure Resource Manager and Microsoft Graph (Using app context or user context depending on what data is needed). I'm using JwtBearer authentication scheme here.
3. I'm using Visual Studio 2022 Version: 17.11.2 and this is all local development.
4. My data layer is Cosmos DB and since all development is local right I'm using the Cosmos DB emulator.
5. Using Microsoft.Identity.Web version 3.1.0 and Microsoft.AspNetCore version 8.0.8
6. The user account I've been testing with is enabled for MFA, and MFA is working/being satisfied during web app authentication.

Problem scenario:

1) Web app signs in user, web app needs to render components that are populated with ARM resources the user has access to so it calls my web api to make the call to ARM through the user's context.
2) Whenever I try getting an access token for the user to pass to the web api so it can request an access token to call ARM, I receive the error below:

Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException
  HResult=0x80131500
  Message=IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent. 
  Source=Microsoft.Identity.Web.TokenAcquisition

Inner Exception 1:
MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call. 

3) What makes absolutely no sense to me is that **just seconds after authenticating to the web app**, I'm getting the MsalUiRequiredException. The app is never running for a long time and no the application isn't being restarted between auth attempts.

**Very important point: Outside of the web app, I have generated a valid access token and inserted that into the headers in the call to my web api and I get a successful response, so this seems to be something specific to the auth library or aspnet.core middleware.**

Initial Program.cs and appSettings.json entraid section:

Program.cs

builder.Services
    .AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("EntraID"), subscribeToOpenIdConnectMiddlewareDiagnosticsEvents: true)
    .EnableTokenAcquisitionToCallDownstreamApi(builder.Configuration.GetSection("MyAPI:Scopes").Get<List<string>>())
    .AddDownstreamApi("MyAPI", builder.Configuration.GetSection("MyAPI"))
    .AddDistributedTokenCaches();
    
(**Note, I was first using .AddInMemoryTokenCaches(); but moved to a Cosmos DB distributed cache in hopes of getting past the issue with silent token request using cache; however, same result)**

"EntraId": {
  "Instance": "https://login.microsoftonline.com/",
  "Domain": "<redacted>.onmicrosoft.com",
  "TenantId": "<redacted>",
  "ClientId": "<redacted>",
  "CallbackPath": "/signin-oidc",
  "SignedOutCallbackPath": "/signout-callback-oidc",
  "ClientCredentials": [
    {
      "SourceType": "Path",
      "CertificateDiskPath": "<redactedPathtoCertificate>.pfx",
      "CertificatePassword": "<redacted>"
    }
  ],
  "EnablePiiLogging": true (Just for tracing in local development)
},

Other notes:

1) I've seen statements on using the MicrosoftIdentityConsentAndConditionalAccessHandler and calling ConsentHandler.HandleException(ex); to trigger the authentication needed. I'm trying this and when this re-authentication happens the user is in the middle of trying to complete a form which in which all data gets lost because of the page reload. Also, it seems the exception is never really "handled" because after repeated re-authentications it seems the user never gets what's needed to satisfy authentication requirements. I'm never prompted to consent for anything nor do I get any errors indicating I have any missing scopes.
2) I've seen statements on using [AuthorizeForScopes] in the api controller. Unfortunately, the call to the api never happens because we fall trying to get a user access token before making the api call.
3) Given #2, the web api never actually being called, ReplyForbiddenWithWwwAuthenticateHeaderAsync never enters the scenario either.
4) I've seen guidance on clearing cookies if an access token can't be retrieved from cache. I implemented some suggestions on that and ended up in an authentication loop. It seems the tokens are never actually cached, or the method to retrieve from cache isn't working correctly. I have trace level logging turned on for Microsoft.Identity and do see cache hits being written to output but again...what's in the cache (If it's being called to service the silent token request) doesn't seem to satisfy whatever conditions are looked for.
5) Initially my app registrations (one for blazor web app, one for web api) were in a different tenant setup as multi-tenant, but I've since moved both apps directly into the tenant where the Azure subscriptions live.

### Reproduction steps

Offending call/steps to repro:

1) Use HttpClientFactory to create an HttpClient (Referencing my web api) to call GetAccessTokenForUserAsync with either of these overloads:

var tokenAcquisitionOptions = new TokenAcquisitionOptions
{
    Tenant = tenantId (Initially the app registrations I was using were multi-tenant and I'm signing in with a guest user so trying to make sure the tenant is explicitly known.
};

//var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(Configuration.GetSection("MyAPI:Scopes").Get<List<string>>(),
//     tokenAcquisitionOptions: tokenAcquisitionOptions);
or
var scopes = Configuration.GetSection("MyAPI:Scopes").Get<List<string>>();
var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(scopes, tenantId, null, authState.User);

I see both id and access tokens being generated and supposedly cached. authState (AuthenticationStateProvider) says I am authenticated, and I can see all claims present.

or

2) Use IDownStreamAPI to make this call:
var tenants = await DownstreamApi.CallApiForUserAsync<List<TenantResource>>("MyAPI",
    options =>
    {
        options.Scopes = Configuration.GetSection("MyAPI:Scopes").Get<List<string>>();
        options.RelativePath = "api/azureResources/tenants";
    });

Both approaches (GetAccessTokenForUserAsync and DownstreamApi.CallApiForUserAsync) result in the same error messages I noted above (MsalUiRequiredException).

Changes to program.cs and appsettings.json:

Based on what I've read and seeing how tokenacquisition's lifetime is scoped, I switched over to this in program.cs:

builder.Services
    .**AddMicrosoftIdentityWebAppAuthentication**(configuration: builder.Configuration,
        configSectionName: "AzureAd", openIdConnectScheme: "OpenIdConnect", cookieScheme: "Cookies",
        subscribeToOpenIdConnectMiddlewareDiagnosticsEvents: true, displayName: "EntraId") (Note: I've set display or left it out, result doesn't change)
    .EnableTokenAcquisitionToCallDownstreamApi(builder.Configuration.GetSection("MyAPI:Scopes").Get<List<string>>())
    .AddDownstreamApi("ArchTechLyticsAPI", builder.Configuration.GetSection("MyAPI"))
    .AddDistributedTokenCaches();

builder.Services.AddTokenAcquisition(true);

appSettings.json

Changed EntraId section to AzureAd since it seems that's the expected name.

Now, with this change I'm receiving IDW10106: The 'ClientId' option must be provided and authentication is more degraded than it was previously.

### Error message

See errors in the description.

### Id Web logs

11:21:05:706	=== Request Data ===
11:21:05:706	Authority Provided? - True
11:21:05:706	Client Id - d2dd4cc2-ad59-4550-a8ba-a88b60883453
11:21:05:706	Scopes - 
11:21:05:706	Redirect Uri - https://localhost:7173/signin-oidc
11:21:05:706	Extra Query Params Keys (space separated) - 
11:21:05:706	ClaimsAndClientCapabilities - 
11:21:05:706	Authority - https://login.microsoftonline.com/f3ff64ce-5a70-4030-88fa-5799d6541cbc/
11:21:05:706	ApiId - AcquireTokenSilent
11:21:05:706	IsConfidentialClient - True
11:21:05:706	SendX5C - False
11:21:05:706	LoginHint - 
11:21:05:706	IsBrokerConfigured - False
11:21:05:706	HomeAccountId - 
11:21:05:706	CorrelationId - 10cd7f07-5866-4638-9613-37df439f0e7a
11:21:05:706	UserAssertion set: False
11:21:05:706	LongRunningOboCacheKey set: False
11:21:05:706	Region configured: 
11:21:05:706	
11:21:05:706	Microsoft.Identity.Web.TokenAcquisition: Information: True MSAL 4.61.3.0 MSAL.NetCore .NET 8.0.8 Microsoft Windows 10.0.22631 [2024-09-12 15:21:05Z - 10cd7f07-5866-4638-9613-37df439f0e7a] === Token Acquisition (SilentRequest) started:
11:21:05:706		Authority: https://login.microsoftonline.com/f3ff64ce-5a70-4030-88fa-5799d6541cbc/
11:21:05:706		Scope: 
11:21:05:706		ClientId: d2dd4cc2-ad59-4550-a8ba-a88b60883453
11:21:05:706		
11:21:05:706	Microsoft.Identity.Web.TokenAcquisition: Debug: True MSAL 4.61.3.0 MSAL.NetCore .NET 8.0.8 Microsoft Windows 10.0.22631 [2024-09-12 15:21:05Z - 10cd7f07-5866-4638-9613-37df439f0e7a] No account passed to AcquireTokenSilent. 
11:21:05:706	Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll
11:21:05:706	Microsoft.Identity.Web.TokenAcquisition: Debug: True MSAL 4.61.3.0 MSAL.NetCore .NET 8.0.8 Microsoft Windows 10.0.22631 [2024-09-12 15:21:05Z - 10cd7f07-5866-4638-9613-37df439f0e7a] Token cache could not satisfy silent request.
11:21:05:706	Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll
11:21:05:706	Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
11:21:05:967	Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
11:21:05:967	Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
11:21:05:967	Microsoft.Identity.Web.TokenAcquisition: Error: True MSAL 4.61.3.0 MSAL.NetCore .NET 8.0.8 Microsoft Windows 10.0.22631 [2024-09-12 15:21:05Z - 10cd7f07-5866-4638-9613-37df439f0e7a] MSAL.NetCore.4.61.3.0.MsalUiRequiredException:
11:21:05:967		ErrorCode: user_null
11:21:05:967	Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call. 
11:21:05:967	   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
11:21:05:967	   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
11:21:05:967	--- End of stack trace from previous location ---
11:21:05:967	   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
11:21:05:967	   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
11:21:05:967		StatusCode: 0 
11:21:05:967		ResponseBody:  
11:21:05:967		Headers: 
11:21:05:967	Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll
11:21:05:967	Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
11:21:05:967	Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
11:21:05:967	Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
11:21:05:967	Microsoft.Identity.Web.TokenAcquisition: Information: [MsIdWeb] An error occured during token acquisition: No account or login hint was passed to the AcquireTokenSilent call. 
11:21:05:967	
11:21:05:967	MSAL.NetCore.4.61.3.0.MsalUiRequiredException:
11:21:05:967		ErrorCode: user_null
11:21:05:967	Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call. 
11:21:05:967	   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
11:21:05:967	   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
11:21:05:967	--- End of stack trace from previous location ---
11:21:05:967	   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
11:21:05:967	   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
11:21:05:967	   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
11:21:05:967	   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForWebAppWithAccountFromCacheAsync(IConfidentialClientApplication application, ClaimsPrincipal claimsPrincipal, IEnumerable`1 scopes, String tenantId, MergedOptions mergedOptions, String userFlow, TokenAcquisitionOptions tokenAcquisitionOptions)
11:21:05:967	   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
11:21:05:967		StatusCode: 0 
11:21:05:967		ResponseBody:  
11:21:05:967		Headers: 
11:21:05:967	Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in Microsoft.Identity.Web.TokenAcquisition.dll
11:21:05:967	Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in System.Private.CoreLib.dll
11:21:05:967	Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in System.Private.CoreLib.dll
11:21:05:967	[2024-09-12T15:21:05.952Z] Information: WebSocket connected to wss://localhost:7173/_blazor?id=ITrtKXvQ2LaEbMs42qsS_w.
11:21:06:216	System.Net.Http.HttpClient.ArchTechLyticsAPI.LogicalHandler: Information: Start processing HTTP request GET https://localhost:7022/api/tenantdetails/f3ff64ce-5a70-4030-88fa-5799d6541cbc
11:21:06:216	System.Net.Http.HttpClient.ArchTechLyticsAPI.ClientHandler: Information: Sending HTTP request GET https://localhost:7022/api/tenantdetails/f3ff64ce-5a70-4030-88fa-5799d6541cbc
11:21:06:216	Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
11:21:06:216	Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
11:21:06:216	Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
11:21:06:216	Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
11:21:06:216	Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
11:21:06:216	Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
11:21:06:216	Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
11:21:06:216	Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.
11:21:06:216	
11:21:06:216	System.ArgumentNullException: IDW10106: The 'ClientId' option must be provided. 
11:21:06:216	   at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options)
11:21:06:216	   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__0(JwtBearerOptions options, IServiceProvider serviceProvider, IMergedOptionsStore mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor)
11:21:06:216	   at Microsoft.Extensions.Options.ConfigureNamedOptions`4.Configure(String name, TOptions options)
11:21:06:216	   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
11:21:06:216	   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
11:21:06:216	--- End of stack trace from previous location ---
11:21:06:216	   at System.Lazy`1.CreateValue()
11:21:06:216	   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
11:21:06:216	   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
11:21:06:216	   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
11:21:06:216	   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
11:21:06:216	   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
11:21:06:216	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
11:21:06:216	   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
11:21:06:216	   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
11:21:06:216	   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### Relevant code snippets

```csharp
See reproduction steps above.
```

### Expected behavior

I expect to be able to sign into a web app, and when the web app needs access to the user's token (Or needs to be able to request a new one) that the web app is silently able to do so...without triggering a re-authentication that never satisfies the original prompt for re-authentication. Effectively, this is an authentication loop.

**Comment by BernieEllis** [comment]
OK, after tons more reading and trying different approaches, seems I had some things in place shooting myself in the foot.

1) My OpenIdConnectOptions seemed to be the major/final culprit. Once I removed the code block below, I started seeing id and access token issued with user context. Perhaps some of the options defined here override/conflicts with the scheme and options provided in .AddAuthentication? This was the cause of the MSALUiRequiredException, the tokens being passed had no user context. Obviously, I still need to add some token validation parameters but will incrementally and carefully add what options I need most.

builder.Services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
  {
      options.SaveTokens = true;
      options.GetClaimsFromUserInfoEndpoint = true;
      options.Authority = "https://login.microsoftonline.com";
      options.Validate();
      options.ResponseType = "code id_token";
      options.Scope.Add("api://myapi/api.access");
      options.ProtocolValidator = new Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator
      {
          RequireStateValidation = false,
          NonceLifetime = TimeSpan.FromMinutes(30),
          RequireNonce = true
      };

      options.TokenValidationParameters = new TokenValidationParameters
      {
          ValidateIssuer = true,
          ValidateTokenReplay = true,
          ValidTypes = new[] { "at+jwt", "JWT" }

      };
      options.Events.OnTokenValidated = context =>
      {
          // Access the claims and add additional processing if needed
          var claimsIdentity = context.Principal.Identity as ClaimsIdentity;
          if (claimsIdentity != null)
          {
             // Process claims as needed
          }
          return Task.CompletedTask;
      };
  });

The above is from my web app and I had a similar block in my web api (Just using Jwt scheme vs. OpenIDConnect). Once I removed it from both, all token acquisition, front end and OBO for my ultimate downstream resource (MS Graph/Azure Resource Manager) worked correctly.

2) Perhaps minor, but I was also getting this error: IDW10203: The 'scope' or 'scp' claim does not contain scopes 'api://<uniqueid/api.access' or was not found. Maybe this is a rookie thing, but I thought I saw guidance about passing fully qualified names for claims. That said, in my controller action I just remove the api://<uniqueid>/ prefix from the scope and just left api.access. 

Final thoughts:

As I mentioned in my initial post of the issue, none of the approaches I tried worked (Well, because my setup was wrong, 100% on me). The main thing I kept coming back to is understanding that Entra ID wasn't seeing my user context (Even though I could see isauthenticated:true in HttpContext). The usual suspects (MFA, Conditional Access, Missing scopes, Missing consent) were not the problem. So, if you find yourself with this error and you're sure the usual suspects are setup correctly, seek to understand why the platform is not seeing your user context.
