### ISSUE TITLE
[Bug] Null reference exception calling AcquireTokenByAuthorizationCode when client secret is not specified (need to improve error message)

### ISSUE THREAD

**Issue by winterlimelight** [AzureAD/microsoft-identity-web#66]
**Which Version of MSAL are you using ?**
4.5.1

**Platform**
.NET Core 3

**What authentication flow has the issue?**
* Web App
    * [ ] Authorization code
 

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**
This is based on https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-with-authorization-codes-on-web-apps but using WithB2CAuthority rather than WithAuthority.

```csharp
IConfidentialClientApplication cca = ConfidentialClientApplicationBuilder
	.Create(AzureAdB2COptions.ClientId)
	.WithRedirectUri(AzureAdB2COptions.RedirectUri)
	.WithB2CAuthority(AzureAdB2COptions.Authority)
	.Build();

var builder = cca.AcquireTokenByAuthorizationCode(new[] { "openid" }, context.ProtocolMessage.Code);
AuthenticationResult result = await builder.ExecuteAsync();
```

**Expected behavior**
I was expecting to retrieve an access token in line with https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oauth-code#2-get-a-token

**Actual behavior**
Exception is thrown by ExecuteAsync(). Stack-trace as follows (awaits removed):
```
at Microsoft.Identity.Client.Internal.ClientCredentialWrapper.get_Thumbprint()
at Microsoft.Identity.Client.Internal.JsonWebToken.JWTHeaderWithCertificate..ctor(ClientCredentialWrapper credential, Boolean sendCertificate)
at Microsoft.Identity.Client.Internal.JsonWebToken.EncodeHeaderToJson(ClientCredentialWrapper credential, Boolean sendCertificate)
at Microsoft.Identity.Client.Internal.JsonWebToken.Encode(ClientCredentialWrapper credential, Boolean sendCertificate)
at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(ClientCredentialWrapper credential, Boolean sendCertificate)
at Microsoft.Identity.Client.Internal.Requests.ClientCredentialHelper.CreateClientCredentialBodyParameters(ICoreLogger logger, ICryptographyManager cryptographyManager, ClientCredentialWrapper clientCredential, String clientId, AuthorityEndpoints endpoints, Boolean sendX5C)
at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendTokenRequestAsync>d__21.MoveNext()
at Microsoft.Identity.Client.Internal.Requests.AuthorizationCodeRequest.<ExecuteAsync>d__3.MoveNext()
at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__14.MoveNext()
at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.<ExecuteAsync>d__2.MoveNext()
```

**Possible Solution**
I had a look at the master (512d74e) and at RequestBase.cs line 300 there is a condition `if (AuthenticationRequestParameters.ClientCredential != null)` which must be succeeding to get that stack trace. I would have expected this to be null as I'm executing AcquireTokenByAuthorizationCode and not a client credentials grant.

The WebApp-OpenIDConnect-DotNet sample includes `.WithClientSecret(AzureAdB2COptions.ClientSecret)` and using this makes the exception go away, but doesn't resolve the problem because it generates an error in B2C: "'AADB2C90079: Clients must send a client_secret when redeeming a confidential grant".

**Comment by jmprieur** [comment]
Re-opening to investigate.
Be more robust on ClientSecret / ClientID

**Comment by kdblocher** [comment]
@pdemro @rmotyka this was my issue as well - I was storing my `ClientSecret` in the user secrets area and after a folder rename / environment change I started getting this exception.

I think informing the caller of a lack of the client secret far earlier would help quite a bit. The error message is quite cryptic.

**Comment by jmprieur** [comment]
@winterlimelight 
@rijulluman-msft 
@rmotyka 
@pdemro 

Fixed in Microsoft.Identity.Web 0.1.2-preview (released today)
