### ISSUE TITLE
[Question] How to handle the MSALUIRequiredException when token is expired

### ISSUE THREAD

**Issue by rajeev16mca2k5** [AzureAD/microsoft-identity-web#843]
**Which version of Microsoft Identity Web are you using?**
Microsoft.Identity.Web 1.4.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [X] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [X] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
New app.

**Repro**

```csharp
services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureAdB2C")
    .AddDistributedTokenCaches();
services.AddDistributedSqlServerCache(options =>
{
    options.ConnectionString = _config["DistCache_ConnectionString"];
    options.SchemaName = "dbo";
    options.TableName = "TestCache";
});
```
We are calling _tokenAcquisition.GetAccessTokenForUserAsync to get the access token. This works.
This method acquires new access token and refresh token automatically, if access token is expired.

But If token cache entry is expired, but still present in database. This method throws MSALUIRequiredException.
(Note: no matters, if access token is still valid or expired. This method generates exception if token cache entry is expired.)

**Expected behavior**
We were expecting this method will do silent login and return us an access token, when token cache entry is expired.
The validity of the token cache should not affect the validity of access token.

**Actual behavior**
GetAccessTokenForUserAsync method is throwing MSALUIRequiredException exception, when token cache entry is expired.

Default expiration of Sql Token Cache is 20 mins. Default Access token expiration is 1 hour.
If we leave everything with default settings and leave application inactive for 20 mins. 
When we perform any action after 20 mins, token cache entry is expired, but access token is still valid.
Calling _tokenAcquisition.GetAccessTokenForUserAsync method at that time throws MSALUIRequiredException exception.

**Possible solution**
When we debugged Microsoft.Identity.Web OpenSource, The value of accountIdentifier looks okay.
But since account is null, we get an exception in GetAccessTokenForUserAsync at Line 219.

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.
Exception
Message - One or more errors occurred. (IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent. )
StackTrace -   at GIXplore.Utility.RequestHandlingMiddleware.Invoke(HttpContext httpContext) in E:\\GeoLogix\\Proj\\Microservices\\GIXplore\\Trunk\\GIXplore\\Utility\\RequestHandlingMiddleware .cs:line 23
   at CommonFiles.ErrorHandlingMiddleware.Invoke(HttpContext httpContext) in E:\\GeoLogix\\Proj\\Common\\Code\\Trunk\\CommonLibrary\\Code\\ErrorHandlingMiddleware.cs:line 20
InnerException
Message - IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent.
StackTrace - at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String tenant, String userFlow, ClaimsPrincipal user) in E:\\GeoLogix\\Proj\\OpenSource\\MSAL\\0.4.0-preview-netcoreonly\\microsoft-identity-web-master\\src\\Microsoft.Identity.Web\\TokenAcquisition.cs:line 265
   at CommonFiles.HttpHelper.GetClient(Boolean isTokenRequired) in E:\\GeoLogix\\Proj\\Common\\Code\\Trunk\\CommonLibrary\\Code\\HttpHelper.cs:line 38
Inner Exception
Message - No account or login hint was passed to the AcquireTokenSilent call.
Error code - user_null.
StackTrace -    at Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder.Validate()
   at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1.ValidateAndCalculateApiId()
   at Microsoft.Identity.Client.AbstractClientAppBaseAcquireTokenParameterBuilder`1.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1.ExecuteAsync()
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForWebAppWithAccountFromCacheAsync(IConfidentialClientApplication application, IAccount account, IEnumerable`1 scopes, String authority, String userFlow) in E:\\GeoLogix\\Proj\\OpenSource\\MSAL\\0.4.0-preview-netcoreonly\\microsoft-identity-web-master\\src\\Microsoft.Identity.Web\\TokenAcquisition.cs:line 536
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForWebAppWithAccountFromCacheAsync(IConfidentialClientApplication application, ClaimsPrincipal claimsPrincipal, IEnumerable`1 scopes, String authority, String userFlow) in E:\\GeoLogix\\Proj\\OpenSource\\MSAL\\0.4.0-preview-netcoreonly\\microsoft-identity-web-master\\src\\Microsoft.Identity.Web\\TokenAcquisition.cs:line 499
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String tenant, String userFlow, ClaimsPrincipal user) in E:\\GeoLogix\\Proj\\OpenSource\\MSAL\\0.4.0-preview-netcoreonly\\microsoft-identity-web-master\\src\\Microsoft.Identity.Web\\TokenAcquisition.cs:line 250

**Comment by jmprieur** [comment]
@rajeev16mca2k5 this is done silently if you add the `[AuthorizeForScope( ...)]` attribute on your controller, Razor page or controller Action.

See https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access which explains what happens, and how to solve it auto-magically.

**Comment by jmprieur** [comment]
Closing this issue as it was answered

**Comment by rajeev16mca2k5** [comment]
> Closing this issue as it was answered

Hi @jmprieur ,

Sorry for the late reply.
This issue is still not resolved. 
We are still getting MSALUIRequired Exception, when SQL Token Cache is expired, but access token is still valid.

I am attaching sample application to reproduce the issue with steps specified in the readme.txt file under project folder.
I have taken off client id and secret for security. If you would like to use our application, please provide an email address where I can send you these details and credentials.

Note: We are using Authorization Code Flow, so during registration of application we deselected both Access Token and ID Token Options used for implicit flow. Attached screenshot.
![image](https://user-images.githubusercontent.com/7395385/105367486-7ff1d580-5c26-11eb-945e-7f9b769bbc98.png)

[MSIdentitySample.zip](https://github.com/AzureAD/microsoft-identity-web/files/5850072/MSIdentitySample.zip)
