### ISSUE TITLE
How to investigate IDX20803: Unable to obtain configuration from: 'System.String'. ?

### ISSUE THREAD

**Issue by Servellia** [AzureAD/microsoft-identity-web#851]
I have a .net core 3.1 Web app, that is connecting to AzureAD. I want to expose this application via a local Kubernetes cluster, where NGINX is used as a reverse proxy. In my configuration I am removing https from the application alltogether to get it to run on http first.

This approach work fine in the following scenarios:

- local debugging
- spinning up in Docker
- docker-compose

However, once I package the application and roll it out to K8s I get the following exception:

```
user@machine:~/$ curl 10.152.183.240/health
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'System.String'.
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.Identity.Web.InstanceDiscovery.IssuerConfigurationRetriever.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync()
   at Microsoft.Identity.Web.Resource.MicrosoftIdentityIssuerValidatorFactory.GetAadIssuerValidator(String aadAuthority)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__0(JwtBearerOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 microsoftIdentityOptionsMonitor)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`3.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Host: 10.152.183.240
User-Agent: curl/7.68.0
```

Looking at the callstack, I am assuming this has something to do with the configuration being passed in, but I cannot explain this to myself, since I've stuck them in the appsettings.json during development and do not touch them

Just to make it complete, here are the manifests, if this is of interest:

```yaml
apiVersion: v1
kind: Service
metadata:
    name: xxx-api-svc
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31112
      name: "http"
    selector:
        app: xxx-api
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: xxx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx-api
  template:
    metadata:
      labels:
        app: xxx-api 
    spec:
      hostname: xxx-api-dev
      containers:
        - name: his-api 
          image: localhost:32000/xxx.api
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "ASPNETCORE_URLS"
            value: "http://+:80"
          ports:
          - containerPort: 80
```

**Comment by jmprieur** [comment]
@Servellia 
- Is it the same question as https://github.com/AzureAD/microsoft-identity-web/issues/850 ?
- What do you have for the authority ?

**Comment by Servellia** [comment]
Yes, that is an accidental duplicate. 

I'm lost in translation - what does "authority" refer to?

**Comment by jmprieur** [comment]
what do you have in your appsettings.json? @Servellia

**Comment by Servellia** [comment]
"AzureAd": {
      "Domain": "enterprisedomain.onmicrosoft.com",
      "ClientId": "xxxxxxxxx-723f-426c-9d8c-d753e4833b9c",
      "ClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.E",
      "Instance": "https://login.microsoftonline.com/",
      "TenantId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
   },

**Comment by jmprieur** [comment]
@Servellia : the tenant Id needs to be the same for the SPA (xxxxxxxxx-xxxxxxxxxx-aac5-b26d20661fe5) and the web API (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx). Is it the case?

**Comment by Servellia** [comment]
Now that the holidays are over, lets get back to the problem at hand. I've gone ahead and done 2 things:

- remove the identity configuration and deploy this to K8s, to make sure it is in fact the Identity configuration, that is causing the problem
- align the instance to be the same as the authority in the React Spa

Now the config looks like this:

```json
"AzureAd": {
      "Domain": "enterprisedomain.onmicrosoft.com",
      "ClientId": "xxxxxxxxx-723f-426c-9d8c-d753e4833b9c",
      "ClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.E",
      "Instance": "https://login.microsoftonline.com/291d05b0-xxxx-xxxx-xxxx-xxxxxxxxxxx",
      "TenantId": "291d05b0-xxxx-xxxx-xxxx-xxxxxxxxxxx"
}
```

TenantId and the id on the instance property are identical. This now results in the following result:

```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1'.
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

**Comment by jmprieur** [comment]
@Servellia 
Instance should be 'https://login.microsoftonline.com/' (without the tenant ID)

**Comment by Servellia** [comment]
The instance is 'https://login.microsoftonline.com/' again. Doing a curl to the configuration surce url results in a valid response:
https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1

```json
{
   "tenant_discovery_endpoint":"https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration",
   "api-version":"1.1",
   "metadata":[
   ]
}
```

**Comment by jmprieur** [comment]
@GeoK @brentschmaltz would you have an idea?

**Comment by GeoK** [comment]
` ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable`
Looks like some sort of networking/routing issue. I can open https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1 in my browser.

**Comment by Servellia** [comment]
I am now at a point, where I am almost certain, that the issue is _not_ Asp.net Core. Microsoft.Identity.Web or any other configuration, but the Microk8s cluster config and DNS, since not pod on that cluster can reach the outside world. 

Theoretically this can be closed. If I can resolve it, I will post the solution here.

**Comment by jmprieur** [comment]
Thanks for the update @Servellia 
Closing as you proposed.

**Comment by Servellia** [comment]
To tie up lose ends:
This was in fact a DNS based problem, although I could not find the cause of it.  I did a reset of the cluster, removed it and reinstalled it. After I've added the ssl certifcates the build pipeline did its magic and eerything went to work.

**Comment by jmprieur** [comment]
Thanks for the update @Servellia !
We're glad you got it working.

**Comment by MomaniNidal** [comment]
@Servellia  Could you help me to solve this issue it's also appear on VM

**Comment by NandanPatel1982** [comment]
Hi Servellia, i am still facing this issue on windows server 2012. any pointers to resolve this issue?

**Comment by Servellia** [comment]
It was infact a DNS issue. The only advise I can give, is to check, that you can resolve login.microsoftonline.com

**Comment by NandanPatel1982** [comment]
from browser when i hit https://login.microsoftonline.com it goes to https://www.office.com/?auth=2 but its uanble to load there where in my local environment it gets loaded. so you mean https://www.office.com/?auth=2 should be accessible ?

**Comment by NandanPatel1982** [comment]
I managed to solve it by changing the application pool identity from "Applicationpoolidentity" to "Built-in Account". in bulit in account service account name and its password is given

**Comment by samercs** [comment]
@NandanPatel1982  Thank you for your reply. It is true when i changed application pool identity from "Applicationpoolidentity" to "Built-in Account", This slove the issue for me. Once again thank you for your comment.

**Comment by samercs** [comment]
> I managed to solve it by changing the application pool identity from "Applicationpoolidentity" to "Built-in Account". in bulit in account service account name and its password is given

Thank you for your reply. It is true when i changed application pool identity from "Applicationpoolidentity" to "Built-in Account", This slove the issue for me. Once again thank you for your comment.
