### ISSUE TITLE
Unhandled Exception When No Outbound Access Permitted

### ISSUE THREAD

**Issue by mbrowntampaairportcom** [AzureAD/microsoft-identity-web#939]
I am developing an application using Microsoft Identity Web and Web UI for authentication. The server does not have unrestricted inbound or outbound access. If I disable the firewall the authentication processes successfully. Running without the firewall enabled is not an option for a production instance. Is there a list of domains and ports that are used in processing an authentication?

I am getting the following exception when trying to process the authentication without outbound access:

Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
EventId: 1
SpanId: 15899443d5ca604a
TraceId: 2ba813b6b51afe45904b8ee0ed79686c
ParentId: 0000000000000000
RequestId: 8000183d-0001-bb00-b63f-84710c7967bb
RequestPath: /

An unhandled exception has occurred while executing the request.

Exception: 
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'System.String'.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.Identity.Web.InstanceDiscovery.IssuerConfigurationRetriever.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync()
   at Microsoft.Identity.Web.Resource.MicrosoftIdentityIssuerValidatorFactory.GetAadIssuerValidator(String aadAuthority)
   at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__2(OpenIdConnectOptions options, IServiceProvider serviceProvider, IOptions`1 microsoftIdentityOptions)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`3.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by jmprieur** [comment]
@mbrowntampaairportcom : It depends if this is a web app or web api

Whatever, the app will go to the Instance (that is Azure AD, as specified in the [appsettings.json](https://github.com/AzureAD/microsoft-identity-web/blob/0d4d0188c6b52b2eda711e591f8d837ed1e7cddf/tests/WebAppCallsWebApiCallsGraph/Client/appsettings.json#L3)). If it's a web app, it will be called on the redirect URI (which is computing from the launch URLs which are in the launchsettings.json in ASP.NET Core applications, or the deployed URL)

If it calls (downstream) APIs, then these endpoints will also be called. See [downstream APIs base URL](https://github.com/AzureAD/microsoft-identity-web/blob/0d4d0188c6b52b2eda711e591f8d837ed1e7cddf/tests/WebAppCallsWebApiCallsGraph/Client/appsettings.json#L30)

Does it help?

**Comment by mbrowntampaairportcom** [comment]
So in that case, the SOLE domain and port that needs to be open would be login.microsoftonline.com and 443 based on the instance of "https://login.microsoftonline.com" in the appsettings.json?

**Comment by mbrowntampaairportcom** [comment]
The code being called in the Blazor application is:

            services.AddMicrosoftIdentityWebAppAuthentication(Configuration);
            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();

**Comment by jmprieur** [comment]
Yes, that should just be https://login.microsoftonline.com, then

**Comment by mbrowntampaairportcom** [comment]
My networking team added a firewall rule permitting traffic to login.microsoft.com port 443 and it does not work. Any other suggestions on how to troubleshoot this to see what traffic is being denied?

**Comment by jmprieur** [comment]
Do you have the possibility of using fiddler?
Or otherwise if it's deployed, do you want to enable App Insights?
